### ISSUE TITLE
Build dependency on bsd/string.h

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-tools#1]
When building xdp-tools, it fails with the following errors:

```
$ make
[...]
make[3]: Entering directory '/home/hawk/git/xdp-tools/lib/util'
cc -I../libbpf/src -Wall -I../../headers -c -o params.o params.c
cc -I../libbpf/src -Wall -I../../headers -c -o logging.o logging.c
cc -I../libbpf/src -Wall -I../../headers -c -o util.o util.c
util.c:9:10: fatal error: bsd/string.h: No such file or directory
 #include <bsd/string.h>
          ^~~~~~~~~~~~~~
compilation terminated.
```

Are there any specific reason for depending on ```bsd/string.h``` ?

**Comment by netoptimizer** [comment]
On Fedora this seems to be avail in package ```libbsd-devel```

```
$ dnf whatprovides '*/bsd/string.h'
[...]
libbsd-devel-0.9.1-2.fc29.i686 : Development files for libbsd
Repo        : fedora
Matched from:
Filename    : /usr/include/bsd/string.h
```

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> On Fedora this seems to be avail in package ```libbsd-devel```
>
> ```
> $ dnf whatprovides '*/bsd/string.h'
> [...]
> libbsd-devel-0.9.1-2.fc29.i686 : Development files for libbsd
> Repo        : fedora
> Matched from:
> Filename    : /usr/include/bsd/string.h
> ```

It's for strlcpy(); can just switch to using regular old strncpy()...

**Comment by netoptimizer** [comment]
> It's for strlcpy(); can just switch to using regular old strncpy()...

Yes, it might be better to reduce dependencies.
