### ISSUE TITLE
ERROR: Can't load eBPF object: No such process(-3)

### ISSUE THREAD

**Issue by kinderg** [xdp-project/xdp-tools#101]
I am very new to eBPF/XDP. I am capturing packets by using XDP dump. Without XDP loading, it is working fine.

But when I run

sudo ./xdp-filter load -m skb eno1
libxdp: Got verifier error while loading dispatcher.
libxdp: Falling back to loading single prog without dispatcher

when I check

 sudo ./xdpdump -D
Interface        Prio  Program name      Mode     ID   Tag               Chain actions
--------------------------------------------------------------------------------------
lo                     xdp_prog_simple   skb      92   3b185187f1855c4c 
eno1                   10     xdpfilt_alw_all    10669 0b394f43ab24501c  XDP_PASS

actually, on interface lo I have loaded XDP program from XDP-tutorial https://github.com/xdp-project/xdp-tutorial/tree/master/basic01-xdp-pass and eno1 with Xdp-dump instructions. But at this time, I only want eno1 Xdp program should work. (for interface lo I run the below command, not interested but mentioning)

 sudo ./xdp_pass_user --dev lo --skb-mode --force
Success: Loading XDP prog name:xdp_prog_simple(id:108) on device:eno1(ifindex:2)

but when I run the below command from Xdp-dump  page instructions I get the below error

sudo ./xdpdump -i eno1 -w - 
ERROR: Can't load eBPF object: No such process(-3)
I cannot understand what I am missing or what I could not understand, without Xdp program loading this command works fine like tcp-dump, but, with loading of XDP program I get the error. I want to capture the packets with loading above Xdp program.

**Comment by chaudron** [comment]
You could use the -vv option to get some more details on why the load has failed, but it probably is related to a kernel feature missing. You need a kernel with at least the following commits:

5b92a28aae4d bpf: Support attaching tracing BPF program to other BPF programs
d831ee84bfc9 bpf: Add bpf_xdp_output() helper
43bc2874e779 bpf: Fix context type resolving for extension programs

**Comment by kinderg** [comment]
yeah, after kernel up-gradation, it is working. Thanks

**Comment by kinderg** [comment]
One more thing, I am doing packet flooding via hping3 and at that time I am capturing packets from XDP dump.
without loading XDP program the results are

sudo ./xdpdump -i eno1 -w - > flood1.pcap | tcpdump -r - -n
tcpdump: truncated dump file; tried to read 4 file header bytes, only got 0
WARNING: Specified interface does not have an XDP program loaded,
capturing in legacy mode!
listening on eno1, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
3750387 packets captured
2124808 packets dropped by kernel


and when I load XDP Program via ( sudo ./xdp-filter load -m skb eno1) the results are:
 sudo ./xdpdump -i eno1 -w - > flood2.pcap | tcpdump -r - -n
tcpdump: truncated dump file; tried to read 4 file header bytes, only got 0
listening on eno1, ingress XDP program ID 99 func xdp_dispatcher, capture mode entry, capture size
262144 bytes
^C^X^
[1]+ Stopped sudo ./xdpdump -i eno1 -w - &gt; attack1.pcap | tcpdump -r - -n

When I check  35432 packets displayed in flood2.pcap file

The flooding time is almost the same as 10 sec almost, but, with loading the Xdp program too low packets captured AS COMPARED to without loading. Why? as mentioned on-page, it is not doing any type of filtering.

**Comment by tohojo** [comment]
kinderg ***@***.***> writes:

> One more thing, I am doing packet flooding via hping3 and at that time I am capturing packets from XDP dump.
> without loading XDP program the results are
>
> sudo ./xdpdump -i eno1 -w - > flood1.pcap | tcpdump -r - -n
> tcpdump: truncated dump file; tried to read 4 file header bytes, only got 0
> WARNING: Specified interface does not have an XDP program loaded,
> capturing in legacy mode!
> listening on eno1, link-type EN10MB (Ethernet), capture size 262144 bytes
> ^C
> 3750387 packets captured
> 2124808 packets dropped by kernel

Erm, you are redirecting the xdpdump output to a file while
simultaneously trying to pipe it to tcpdump? Pretty sure the numbers you
get out of that are entirely bogus.

If you want to both save and display the results you'd need to do
something like:

sudo ./xdpdump -i eno1 -w - | tee flood1.pcap | tcpdump -r - -n

**Comment by zez3** [comment]
> 
> 
> You could use the -vv option to get some more details on why the load has failed, but it probably is related to a kernel feature missing. You need a kernel with at least the following commits:
> 
> 5b92a28aae4d bpf: Support attaching tracing BPF program to other BPF programs
> d831ee84bfc9 bpf: Add bpf_xdp_output() helper
> 43bc2874e779 bpf: Fix context type resolving for extension programs

my Ubuntu 20.04 LTS needed the 5.10 kernel to properly work
