### ISSUE TITLE
Ubuntu dependencies seem incorrect

### ISSUE THREAD

**Issue by mcgov** [xdp-project/xdp-tools#104]
Building with Ubuntu (18.04), dependencies in docs are listed as:
```
sudo apt install clang llvm libelf-dev libpcap-dev gcc-multilib build-essential
sudo apt install linux-tools-$(uname -r) -y
sudo apt install linux-headers-$(uname -r) -y
sudo apt install linux-tools-common linux-tools-generic -y
```
Installing these and attempting to configure, it's missing m4. Install m4 configures and `make` results in this error:
```
    CLANG    xdp-dispatcher.o
In file included from xdp-dispatcher.c:5:
../libbpf/src/root/usr/include/bpf/bpf_helpers.h:99:10: error: unknown register name 'r0' in asm
                     : "r0", "r1", "r2", "r3", "r4", "r5");
                       ^
1 error generated.
```

Am I missing something? It seems like I've missed a step but I don't see it. Any help is appreciated.

**Comment by tohojo** [comment]
Think this is because you need a newer version of clang - IIRC clang 10 is enough, but might as well go for 11. There's an apt repository you can install at apt.llvm.org :)

**Comment by mcgov** [comment]
You are correct! It bugs me that the default version is 6 and `sudo apt install clang-10` doesn't automatically point `clang` to this installation without explicitly adding it to the path, even when the older clang isn't installed. Still, that seems like an ubuntu problem not an xdp-tools problem.
