### ISSUE TITLE
Couldn't load BPF program: Unknown error 4001

### ISSUE THREAD

**Issue by micah** [xdp-project/xdp-tools#106]
Hi, 

I'm trying to load xdp-filter on my interfaces. I'm able to attach xdp programs that I've written and then loaded with `ip link set dev eth11 xdp obj block.o` and they do work properly.

However, when I try to run xdp-filter, I get this:

```
./xdp-filter load eth11
Couldn't load BPF program: Unknown error 4001
```

I'll note that before I ran that, I did remove any running xdp programs (`ip link set dev eth11 xdp off`)

**Comment by tohojo** [comment]
Could you please re-run with -vv and post the full output? What kernel version is this?

**Comment by micah** [comment]
Here you go:

```
Current rlimit 67108864 already >= minimum 1048576
Couldn't open pin directory /sys/fs/bpf/xdp-filter/programs/eth10: No such file or directory
Looking for eBPF program with features tcp,udp,ipv6,ipv4,ethernet,allow
Found prog 'xdpfilt_alw_all.o' matching feature set to be loaded on interface 'eth10'.
libxdp: Looking for './xdpfilt_alw_all.o'
libxdp: Loading XDP program from './xdpfilt_alw_all.o' section 'xdp_filter'
libbpf: loading ./xdpfilt_alw_all.o
libbpf: elf: section(3) xdp_filter, size 3440, link 0, flags 6, type=1
libbpf: sec 'xdp_filter': failed to find program symbol at offset 0
Couldn't load BPF program: Unknown error 4001
```

This is 4.19.0-14-amd64 from Debian stable.

**Comment by tohojo** [comment]
micah ***@***.***> writes:

> Here you go:
>
> ```
> Current rlimit 67108864 already >= minimum 1048576
> Couldn't open pin directory /sys/fs/bpf/xdp-filter/programs/eth10: No such file or directory
> Looking for eBPF program with features tcp,udp,ipv6,ipv4,ethernet,allow
> Found prog 'xdpfilt_alw_all.o' matching feature set to be loaded on interface 'eth10'.
> libxdp: Looking for './xdpfilt_alw_all.o'
> libxdp: Loading XDP program from './xdpfilt_alw_all.o' section 'xdp_filter'
> libbpf: loading ./xdpfilt_alw_all.o
> libbpf: elf: section(3) xdp_filter, size 3440, link 0, flags 6, type=1
> libbpf: sec 'xdp_filter': failed to find program symbol at offset 0
> Couldn't load BPF program: Unknown error 4001
> ```

Looks like you need a newer version of LLVM to compile it with. There's
a handy repository at apt.llvm.org :)

**Comment by micah** [comment]
Ok, thanks! Might be useful to add something to configure to check the dependencies are properly satisfied!

**Comment by tohojo** [comment]
micah ***@***.***> writes:

> Ok, thanks! Might be useful to add something to configure to check the
> dependencies are properly satisfied!

Yup, you're quite right... will add :)
