### ISSUE TITLE
xdp-dump: No BTF found for program

### ISSUE THREAD

**Issue by vrngupta53** [xdp-project/xdp-tools#109]
I dont have BTF enabled in my kernel. Is there any way to use xdp-dump without BTF?

**Comment by tohojo** [comment]
I don't think you need BTF enabled for the kernel itself, but you need it for the XDP programs you're trying to dump - and the rest of xdp-tools won't function without BTF either...

**Comment by vrngupta53** [comment]
Oh, I didnt know the difference there. Thanks!. But I am facing the same issue even after including BTF info in the object file. This is my bpf program drop_packets.c
```
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

SEC("drop")
int xdp_prog_drop(struct xdp_md *ctx) {
    return XDP_DROP;
}
```

I compile this using 
```
clang -S \
    -target bpf \
    -D __BPF_TRACING__ \
    -I../libbpf/src//build/usr/include/ -I../headers/ \
    -Wall \
    -Wno-unused-value \
    -Wno-pointer-sign \
    -Wno-compare-distinct-pointer-types \
    -Werror \
    -O2 -emit-llvm -c -g -o drop_packets.ll drop_packets.c
llc -march=bpf -mattr=dwarfris -filetype=obj -o drop_packets.o drop_packets.ll
```
And then run 
`pahole -J drop_packets.o`
Running `readelf -a drop_packets.o` clearly shows a .BTF section in the object file. But when I load this on the 'lo' device interface, xdp-dump still gives me the same output, no BTF found for program. 
```
sudo ./xdpdump -i lo -p xdp_prog_drop -x -v
>Current rlimit 67108864 already >= minimum 1048576
>No BTF found for program
>No BTF found for program
>ERROR: Can't identify the full XDP 'xdp_prog_drop' function!
>The following is a list of candidates:
>No BTF found for program
>Please use the -p option to pick the correct one.
```
My guess is the loader cannot load the BTF info in the kernel because BTF debug info is disabled in my kernel. Is there some workaround for this?

**Comment by chaudron** [comment]
How are you loading your program? I think "ip" might not load the BTF information. Does bpftool show that the BTF information is present?

Can you load it with xdp-loader and try? Guess the -p option is not showing you anything, as no BTF info is found.

**Comment by vrngupta53** [comment]
Output from bpftool
```
> bpftool btf dump file drop_packets.o                                                            
[1] PTR '(anon)' type_id=2
[2] STRUCT 'xdp_md' size=20 vlen=5
	'data' type_id=3 bits_offset=0
	'data_end' type_id=3 bits_offset=32
	'data_meta' type_id=3 bits_offset=64
	'ingress_ifindex' type_id=3 bits_offset=96
	'rx_queue_index' type_id=3 bits_offset=128
[3] TYPEDEF '__u32' type_id=4
[4] INT 'unsigned int' size=4 bits_offset=0 nr_bits=32 encoding=(none)
[5] FUNC_PROTO '(anon)' ret_type_id=6 vlen=1
	'ctx' type_id=1
[6] INT 'int' size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[7] FUNC 'xdp_prog_drop' type_id=5
```
Then loading it with xdp-loader, 
```
> sudo ./xdp-loader load -m skb lo drop_packets.o
libxdp: Compatibility check for dispatcher program failed: Argument list too long
libxdp: Falling back to loading single prog without dispatcher
> sudo ./xdp-loader status                                                                                             
CURRENT XDP PROGRAM STATUS:

Interface        Prio  Program name      Mode     ID   Tag               Chain actions
--------------------------------------------------------------------------------------
lo                     xdp_prog_drop     skb      61   3b185187f1855c4c 
enp2s0f1               <No XDP program loaded!>
wlp3s0                 <No XDP program loaded!>
br-2f8746b52bff        <No XDP program loaded!>
docker0                <No XDP program loaded!>

```

Trying to attach xdp-dump, 
```
> sudo ./xdpdump -i lo -p xdp_prog_drop -x -v                                            
Current rlimit 67108864 already >= minimum 1048576
Found func xdp_prog_drop matching xdp_prog_drop
Looking for './xdpdump_bpf.o'
Loading bpf file 'xdpdump_bpf.o' from './xdpdump_bpf.o'
ERROR: Can't load eBPF object: No such process(-3)
```

The BTF info is getting loaded I guess, but there is this new error now that I have no clue about. Any suggestions would be very helpful.

**Comment by tohojo** [comment]
Varun Gupta ***@***.***> writes:

> Output from bpftool
> ```
>> bpftool btf dump file drop_packets.o                                                            
> [1] PTR '(anon)' type_id=2
> [2] STRUCT 'xdp_md' size=20 vlen=5
> 	'data' type_id=3 bits_offset=0
> 	'data_end' type_id=3 bits_offset=32
> 	'data_meta' type_id=3 bits_offset=64
> 	'ingress_ifindex' type_id=3 bits_offset=96
> 	'rx_queue_index' type_id=3 bits_offset=128
> [3] TYPEDEF '__u32' type_id=4
> [4] INT 'unsigned int' size=4 bits_offset=0 nr_bits=32 encoding=(none)
> [5] FUNC_PROTO '(anon)' ret_type_id=6 vlen=1
> 	'ctx' type_id=1
> [6] INT 'int' size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
> [7] FUNC 'xdp_prog_drop' type_id=5
> ```
> Then loading it with xdp-loader, 
> ```
>> sudo ./xdp-loader load -m skb lo drop_packets.o
> libxdp: Compatibility check for dispatcher program failed: Argument list too long
> libxdp: Falling back to loading single prog without dispatcher

This indicates that you are running on a rather old kernel...

>> sudo ./xdp-loader status                                                                                             
> CURRENT XDP PROGRAM STATUS:
>
> Interface        Prio  Program name      Mode     ID   Tag               Chain actions
> --------------------------------------------------------------------------------------
> lo                     xdp_prog_drop     skb      61   3b185187f1855c4c 
> enp2s0f1               <No XDP program loaded!>
> wlp3s0                 <No XDP program loaded!>
> br-2f8746b52bff        <No XDP program loaded!>
> docker0                <No XDP program loaded!>
>
> ```
>
> Trying to attach xdp-dump, 
> ```
>> sudo ./xdpdump -i lo -p xdp_prog_drop -x -v                                            
> Current rlimit 67108864 already >= minimum 1048576
> Found func xdp_prog_drop matching xdp_prog_drop
> Looking for './xdpdump_bpf.o'
> Loading bpf file 'xdpdump_bpf.o' from './xdpdump_bpf.o'
> ERROR: Can't load eBPF object: No such process(-3)
> ```

...which means that this is probably also because of that. So I think
you're going to have to upgrade your kernel to use xdpdump - which
version are you running on?

**Comment by vrngupta53** [comment]
Its 5.4.0-71-generic. Which version would I need at least?

**Comment by tohojo** [comment]
Hmm, I think the feature went into 5.7; @chaudron do you recall?

Certainly you're fine if you jump to the next LTS release (5.10)

**Comment by chaudron** [comment]
The last commit I did for xdp-dump support was 43bc2874e779.
So checking the build I would say 5.10:

```
$ git tag --contains 43bc2874e779  | grep -v "\-rc"
net-next-5.11
v5.10
v5.11
```

**Comment by tohojo** [comment]
Eelco Chaudron ***@***.***> writes:

> The last commit I did for xdp-dump support was 43bc2874e779.
> So checking the build I would say 5.10:

Ah, right; I must have gotten the versions confused with the multiprog
support itself...

**Comment by chaudron** [comment]
Assuming the issue was resolved, if not please update. Will close for now.
