### ISSUE TITLE
Not capture traffic of both sides in case of container interface

### ISSUE THREAD

**Issue by Tf-arch** [xdp-project/xdp-tools#110]
I have a cluster setup, I am using docker image of hping3 and place its pod (with IP 10.32.0.2) on one Node-1 (container), Secondly, I am using Nginx server image and place its pod (with IP 10.46.0.1) on another Node-2 (container). 

Through first `Node-1 pod I am flooding packets to the container of second Node (means Nginx server node). 

On Node-2 (means Nginx server node), in its container Interface vethwe-datapath I have loaded an XDP program  by 

xdp-filter load --mode skb vethwe-datapath   , As you can see,

![image](https://user-images.githubusercontent.com/83109300/115949241-187d4780-a4ed-11eb-8f71-afd4e77cb8db.png)

The problem is that it captures  ONLY ONE side traffic, As you can see

with sudo ./xdpdump -i vethwe-datapath -w - | tee ab.pcap | tcpdump -r - -n

![image](https://user-images.githubusercontent.com/83109300/115949345-f506cc80-a4ed-11eb-8516-41a31659b45f.png)

but without loading an XDP-program It captures both sides ingoing outgoing as you can see

with sudo ./xdpdump -i vethwe-datapath -w - | tee ab.pcap | tcpdump -r - -n

![image](https://user-images.githubusercontent.com/83109300/115949379-37c8a480-a4ee-11eb-97db-234e17c0c0de.png)

Why why why? Without loading it works fine and give me traffic of both directions but with loading It captures only one side of traffic? I want to capture both sides by loading an XDP-program

Thank you,

**Comment by alexforster** [comment]
In order to "see" both directions of traffic passing through a veth pair in XDP, you must attach to both veth interfaces.

**Comment by tohojo** [comment]
Tf-arch ***@***.***> writes:

> Why why why? Without loading it works fine and give me traffic of both
> directions but with loading It captures only one side of traffic? I
> want to capture both sides by loading an XDP-program

My guess would be because xdpdump falls back to regular libpcap-based
dump? What version of xdp-tools are you using, and what's the output
when you run it with '-vv'?

**Comment by chaudron** [comment]
> Tf-arch ***@***.***> writes:
> Why why why? Without loading it works fine and give me traffic of both directions but with loading It captures only one side of traffic? I want to capture both sides by loading an XDP-program
> My guess would be because xdpdump falls back to regular libpcap-based dump? What version of xdp-tools are you using, and what's the output when you run it with '-vv'?

Yes, If no XDP program is loaded xdpdump falls back to using libpcap by default (see the warning) and this will capture in both directions. XDP is only taking ingress packets, so that is all you will see. Once XDP supports egress I will enhance xdpdump to also capture packets at egress.

**Comment by Tf-arch** [comment]
Okay, Thank you all for the responses and I got some points., specially XDP captures only ingress packets.

@tohojo  The output of -vv is

Current rlimit 67108864 already >= minimum 1048576
libxdp: Verified XDP dispatcher version 1 <= 1
libxdp: DATASEC '.xdp_run_config' not found.
libxdp: Acquired lock from /sys/fs/bpf/xdp with fd 5
libxdp: Reading multiprog component programs from pinned directory
libxdp: Found func xdpfilt_alw_all matching xdpfilt_alw_all
libxdp: Released lock fd 5
libxdp: Found multiprog with id 21 and 1 component progs
Found func xdp_dispatcher matching xdp_dispatcher
Looking for './xdpdump_bpf.o'
Loading bpf file 'xdpdump_bpf.o' from './xdpdump_bpf.o'
libbpf: loading ./xdpdump_bpf.o
libbpf: elf: section(3) fentry/func, size 304, link 0, flags 6, type=1
libbpf: sec 'fentry/func': found program 'trace_on_entry' at insn offset 0 (0 bytes), code size 38 insns (304 bytes)
libbpf: elf: section(4) .relfentry/func, size 32, link 26, flags 0, type=9
libbpf: elf: section(5) fexit/func, size 320, link 0, flags 6, type=1
libbpf: sec 'fexit/func': found program 'trace_on_exit' at insn offset 0 (0 bytes), code size 40 insns (320 bytes)
libbpf: elf: section(6) .relfexit/func, size 32, link 26, flags 0, type=9
libbpf: elf: section(7) maps, size 20, link 0, flags 3, type=1
libbpf: elf: section(8) license, size 4, link 0, flags 3, type=1
libbpf: license of ./xdpdump_bpf.o is GPL
libbpf: elf: section(9) .data, size 12, link 0, flags 3, type=1
libbpf: elf: section(18) .BTF, size 1801, link 0, flags 0, type=1
libbpf: elf: section(20) .BTF.ext, size 1132, link 0, flags 0, type=1
libbpf: elf: section(26) .symtab, size 1896, link 1, flags 0, type=2
libbpf: looking for externs among 79 symbols...
libbpf: collected 0 externs total
libbpf: elf: found 1 legacy map definitions (20 bytes) in ./xdpdump_bpf.o
libbpf: map 'xdpdump_perf_map' (legacy): at sec_idx 7, offset 0.
libbpf: map 78 is "xdpdump_perf_map"
libbpf: map 'xdpdump_.data' (global data): at sec_idx 9, offset 0, flags 400.
libbpf: map 1 is "xdpdump_.data"
libbpf: sec '.relfentry/func': collecting relocation for section(3) 'fentry/func'
libbpf: sec '.relfentry/func': relo #0: insn #7 against 'trace_cfg'
libbpf: prog 'trace_on_entry': found data map 1 (xdpdump_.data, sec 9, off 0) for insn 7
libbpf: sec '.relfentry/func': relo #1: insn #32 against 'xdpdump_perf_map'
libbpf: prog 'trace_on_entry': found map 0 (xdpdump_perf_map, sec 7, off 0) for insn #32
libbpf: sec '.relfexit/func': collecting relocation for section(5) 'fexit/func'
libbpf: sec '.relfexit/func': relo #0: insn #8 against 'trace_cfg'
libbpf: prog 'trace_on_exit': found data map 1 (xdpdump_.data, sec 9, off 0) for insn 8
libbpf: sec '.relfexit/func': relo #1: insn #34 against 'xdpdump_perf_map'
libbpf: prog 'trace_on_exit': found map 0 (xdpdump_perf_map, sec 7, off 0) for insn #34
libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux': 0
libbpf: map:xdpdump_perf_map container_name:____btf_map_xdpdump_perf_map cannot be found in BTF. Missing BPF_ANNOTATE_KV_PAIR?
libbpf: map 'xdpdump_perf_map': created successfully, fd=7
libbpf: map 'xdpdump_.data': created successfully, fd=8
libbpf: sec 'fentry/func': found 6 CO-RE relocations
libbpf: prog 'trace_on_entry': relo #0: kind <byte_off> (0), spec is [6] struct xdp_buff.data (0:0 @ offset 0)
libbpf: CO-RE relocating [6] struct xdp_buff: found target candidate [21589] struct xdp_buff
libbpf: prog 'trace_on_entry': relo #0: matching candidate #0 [21589] struct xdp_buff.data (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #0: patched insn #1 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_entry': relo #1: kind <byte_off> (0), spec is [6] struct xdp_buff.data_end (0:1 @ offset 8)
libbpf: prog 'trace_on_entry': relo #1: matching candidate #0 [21589] struct xdp_buff.data_end (0:1 @ offset 8)
libbpf: prog 'trace_on_entry': relo #1: patched insn #2 (LDX/ST/STX) off 8 -> 8
libbpf: prog 'trace_on_entry': relo #2: kind <byte_off> (0), spec is [6] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_entry': relo #2: matching candidate #0 [21589] struct xdp_buff.rxq (0:4 @ offset 32)
libbpf: prog 'trace_on_entry': relo #2: patched insn #4 (LDX/ST/STX) off 40 -> 32
libbpf: prog 'trace_on_entry': relo #3: kind <byte_off> (0), spec is [10] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: CO-RE relocating [10] struct xdp_rxq_info: found target candidate [3321] struct xdp_rxq_info
libbpf: prog 'trace_on_entry': relo #3: matching candidate #0 [3321] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #3: patched insn #5 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_entry': relo #4: kind <byte_off> (0), spec is [14] struct net_device.ifindex (0:0 @ offset 0)
libbpf: CO-RE relocating [14] struct net_device: found target candidate [2902] struct net_device
libbpf: prog 'trace_on_entry': relo #4: matching candidate #0 [2902] struct net_device.ifindex (0:22 @ offset 256)
libbpf: prog 'trace_on_entry': relo #4: patched insn #6 (LDX/ST/STX) off 0 -> 256
libbpf: prog 'trace_on_entry': relo #5: kind <byte_off> (0), spec is [10] struct xdp_rxq_info.queue_index (0:1 @ offset 8)
libbpf: prog 'trace_on_entry': relo #5: matching candidate #0 [3321] struct xdp_rxq_info.queue_index (0:1 @ offset 8)
libbpf: prog 'trace_on_entry': relo #5: patched insn #15 (LDX/ST/STX) off 8 -> 8
libbpf: sec 'fexit/func': found 6 CO-RE relocations
libbpf: prog 'trace_on_exit': relo #0: kind <byte_off> (0), spec is [6] struct xdp_buff.data (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #0: matching candidate #0 [21589] struct xdp_buff.data (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #0: patched insn #2 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_exit': relo #1: kind <byte_off> (0), spec is [6] struct xdp_buff.data_end (0:1 @ offset 8)
libbpf: prog 'trace_on_exit': relo #1: matching candidate #0 [21589] struct xdp_buff.data_end (0:1 @ offset 8)
libbpf: prog 'trace_on_exit': relo #1: patched insn #3 (LDX/ST/STX) off 8 -> 8
libbpf: prog 'trace_on_exit': relo #2: kind <byte_off> (0), spec is [6] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_exit': relo #2: matching candidate #0 [21589] struct xdp_buff.rxq (0:4 @ offset 32)
libbpf: prog 'trace_on_exit': relo #2: patched insn #5 (LDX/ST/STX) off 40 -> 32
libbpf: prog 'trace_on_exit': relo #3: kind <byte_off> (0), spec is [10] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #3: matching candidate #0 [3321] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #3: patched insn #6 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_exit': relo #4: kind <byte_off> (0), spec is [14] struct net_device.ifindex (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #4: matching candidate #0 [2902] struct net_device.ifindex (0:22 @ offset 256)
libbpf: prog 'trace_on_exit': relo #4: patched insn #7 (LDX/ST/STX) off 0 -> 256
libbpf: prog 'trace_on_exit': relo #5: kind <byte_off> (0), spec is [10] struct xdp_rxq_info.queue_index (0:1 @ offset 8)
libbpf: prog 'trace_on_exit': relo #5: matching candidate #0 [3321] struct xdp_rxq_info.queue_index (0:1 @ offset 8)
libbpf: prog 'trace_on_exit': relo #5: patched insn #17 (LDX/ST/STX) off 8 -> 8
libxdp: Verified XDP dispatcher version 1 <= 1
libxdp: DATASEC '.xdp_run_config' not found.
libxdp: Acquired lock from /sys/fs/bpf/xdp with fd 14
libxdp: Reading multiprog component programs from pinned directory
libxdp: Found func xdpfilt_alw_all matching xdpfilt_alw_all
libxdp: Released lock fd 14
libxdp: Found multiprog with id 21 and 1 component progs
listening on vethwe-datapath, ingress XDP program ID 21 func xdp_dispatcher, capture mode entry, capture size 262144 bytes
perf-wakeup value uses is 1
reading from file -, link-type EN10MB (Ethernet)




@alexforster  What I am seeing is that,
Now I have loaded XDP program to veth-bridge and veth datapath

check 
![image](https://user-images.githubusercontent.com/83109300/116046826-4a46f900-a628-11eb-9836-139309f5bb3e.png)

and when I capture from veth-datapath result is same as I described above  
(extremely sorry for changing the IPs, for some reason I have refreshed the cluster,  this time Node-2-Nginx server pod IP is  10.34.0.1,                                      and  Node-1 hping3 Pod IP is 10.46.0.0)
![image](https://user-images.githubusercontent.com/83109300/116047065-8a0de080-a628-11eb-917a-b7d760c94ed4.png)

and when I capture from  veth-bridge interface I got other side of traffic as you can see
![image](https://user-images.githubusercontent.com/83109300/116048242-d574be80-a629-11eb-96f8-3944d3bc5444.png)


So, means I got one side traffic from veth-datapath and other side from veth-bridge


@alexforster @tohojo @chaudron  could you help me to understand this behavior??

**Comment by tohojo** [comment]
XDP captures packets on ingress. A bridge sees all traffic as ingress (before forwarding it)...

**Comment by Tf-arch** [comment]
Ok, Thanks a lot!
