### ISSUE TITLE
libxdp: Get queue num from sys in xsk while driver not implement get_channels?

### ISSUE THREAD

**Issue by arikachen** [xdp-project/xdp-tools#123]
I found some driver has fixed queue num like ixgbevf and it not implement get_channels interface. 
Does we need to adapt this situation?

```
static int get_queue(const char* ifname) {
        DIR *dir;
        struct dirent *entry;
        char buf[64];
        int rx, tx;

        sprintf(buf, "/sys/class/net/%s/queues/", ifname);
        dir = opendir(buf);
        if(dir == NULL)
        {
                return 1;
        }
        while((entry=readdir(dir)))
        {
                if (0 == strncmp(entry->d_name, "rx", 2)) {
                        rx++;
                }
                if (0 == strncmp(entry->d_name, "tx", 2)) {
                        tx++;
                }
        }
        closedir(dir);
        // rx tx is zero ?
        return rx > tx ? rx : tx;
}

static int xsk_get_max_queues(struct xsk_socket *xsk)
...
if (err) {
        ret = get_queue(ctx->ifname) 
}
...
```

**Comment by magnus-karlsson** [comment]
That is a good idea. Did not know there was support for ZC on a device without get_channels. Question is if it would not be easier to implement get_channels (but not set_channels) on that device. On the other hand, your approach would support users with older kernels/drivers which is good. So I say, submit a patch please. But use snprintf() to avoid buffer overruns. And "/* */" as comments :-).

Thanks: Magnus
