### ISSUE TITLE
XDP-filter  IP Address

### ISSUE THREAD

**Issue by Tf-arch** [xdp-project/xdp-tools#125]
I want to use XDP-filter with XDP-dump. I am confused with XDP filter options, I want to filter traffic from one specific IP 10.32.0.3. Filter in a sence of drop. Means when I capture trafiic fromXDP-dump then all traffic should be received except from IP 10.32.0.3. I donot want to receive traffic from 10.32.0.3.

so, I have loaded XDP-program and uses command
sudo ./xdp-filter load vethwe-bridge -f tcp,udp
sudo ./xdp-filter load vethwe-datapath -f tcp,udp
then,
sudo ./xdp-filter ip 10.32.0.3 -m src

status
![image](https://user-images.githubusercontent.com/83109300/134359937-6b06bb5e-15a1-4aed-a50e-d81f476ebe4f.png)

so, now if, I will capture traffic from veth interfaces through xdp-dump,
 I will not receive traffic from 10.32.0.3? Am I right?

**Comment by chaudron** [comment]
By default, XDP dump will attach to the entry of the XDP program, so you will see all packets. If you would like to see only packets after the program has run, you should set --rx-capture to exit.

**Comment by tohojo** [comment]
Eelco Chaudron ***@***.***> writes:

> By default, XDP dump will attach to the entry of the XDP program, so
> you will see all packets. If you would like to see only packets after
> the program has run, you should set --rx-capture to exit.

Note that even in this case you'll still see the traffic, it'll just
carry a DROP verdict for the packets that xdp-filter decided to drop.
There's currently no way to attach a filter to xdp-dump so that it only
captures a subset of the traffic (like with tcpdump)...

**Comment by Tf-arch** [comment]
Ok, thanks. Could you tell me is it fast in a sense of packet capturing as compared to tcp-dump?

**Comment by chaudron** [comment]
> Ok, thanks. Could you tell me is it fast in a sense of packet capturing as compared to tcp-dump?

Not sure how you would define fast, but it's faster than tcpdump in the sense it captures the packet right after the driver receives them, and it uses a ring buffer rather than a socket to get the packets to userspace.
