### ISSUE TITLE
Error when linking with libxdp

### ISSUE THREAD

**Issue by cloftus** [xdp-project/xdp-tools#135]
When linking with libxdp, two errors are generated:
```
cc -Wl,--no-as-needed -lxdp
/usr/bin/ld: /usr/local/lib/libxdp.so: undefined reference to `try_snprintf'
/usr/bin/ld: /usr/local/lib/libxdp.so: undefined reference to `silence_libbpf_logging'
```

objdump confirms they are undefined:
```
objdump -t /usr/local/lib/libxdp.so | grep try_snprintf
000000000000a710 l F .text 00000000000000da try_snprintf
0000000000000000 *UND* 0000000000000000 try_snprintf

objdump -t /usr/local/lib/libxdp.so | grep silence_libbpf
0000000000000000 *UND* 0000000000000000 silence_libbpf_logging
```

The call to try_snprintf was introduced to xsk.c in:
fdd1566dcd1f ("libxdp: get queue num from sysfs in xsk")

The call to silence_libbpf_logging in xsk.c was introduced in:
ea481a18ed07 ("libxdp: move AF_XDP functionality from libbpf")

**Comment by tohojo** [comment]
Ciara Loftus ***@***.***> writes:

> When linking with libxdp, two errors are generated:
> ```
> cc -Wl,--no-as-needed -lxdp
> /usr/bin/ld: /usr/local/lib/libxdp.so: undefined reference to `try_snprintf'
> /usr/bin/ld: /usr/local/lib/libxdp.so: undefined reference to `silence_libbpf_logging'
> ```
>
> objdump confirms they are undefined:
> ```
> objdump -t /usr/local/lib/libxdp.so | grep try_snprintf
> 000000000000a710 l F .text 00000000000000da try_snprintf
> 0000000000000000 *UND* 0000000000000000 try_snprintf
>
> objdump -t /usr/local/lib/libxdp.so | grep silence_libbpf
> 0000000000000000 *UND* 0000000000000000 silence_libbpf_logging
> ```
>
> The call to try_snprintf was introduced to xsk.c in:
> fdd1566dcd1f ("libxdp: get queue num from sysfs in xsk")
>
> The call to silence_libbpf_logging in xsk.c was introduced in:
> ea481a18ed07 ("libxdp: move AF_XDP functionality from libbpf")

Oops, that's embarrassing! Those definitely shouldn't be there at all...

**Comment by cloftus** [comment]
Are there any plans in the near future to tag v1.3.0 of xdp-tools/libxdp? I'm working on a patch for the March release of DPDK (22.03) which links with libxdp if it's available on the system. We need a way to determine that this fix is present in libxdp before attempting to link, since linking will fail if it isn't present. The easiest way would be to check for a release >= v1.3.0.

Thanks,
Ciara

**Comment by tohojo** [comment]
Yup, planning to tag a release this week; just got one or two issues to sort out first :)
