### ISSUE TITLE
Make fails with a strange error

### ISSUE THREAD

**Issue by samy-mohsen** [xdp-project/xdp-tools#142]
I get this error when trying to compile the project:

```
lib

  libbpf
    CC       libbpf/src/libbpf.a
    INSTALL  libbpf/src/libbpf.a

  libxdp
    CC       staticobjs/libxdp.o
    CC       staticobjs/xsk.o
    LINK     libxdp.a
    CC       sharedobjs/libxdp.o
    CC       sharedobjs/xsk.o
    LINK     libxdp.so.1.2.0
    M4       xdp-dispatcher.c
    CLANG    xdp-dispatcher.o
    LLC      xdp-dispatcher.o
llc: xdp-dispatcher.ll:15:54: error: expected ')' at end of argument list
define dso_local i32 @prog0(%struct.xdp_md* readnone %0) local_unnamed_addr #0 !dbg !47 {
                                                     ^
Makefile:134: recipe for target 'xdp-dispatcher.o' failed
make[2]: *** [xdp-dispatcher.o] Error 1
Makefile:16: recipe for target 'libxdp' failed
make[1]: *** [libxdp] Error 2
Makefile:25: recipe for target 'lib' failed
make: *** [lib] Error 2

```
I tried multiple times from scratch, got the same issue. I am using Clang and LLVM version 10, on Ubuntu 18.04.6. What could possible be the issue?

**Comment by tohojo** [comment]
Mohamed Samy Mohsen ***@***.***> writes:

> I get this error when trying to compile the project:
>
> ```
> lib
>
>   libbpf
>     CC       libbpf/src/libbpf.a
>     INSTALL  libbpf/src/libbpf.a
>
>   libxdp
>     CC       staticobjs/libxdp.o
>     CC       staticobjs/xsk.o
>     LINK     libxdp.a
>     CC       sharedobjs/libxdp.o
>     CC       sharedobjs/xsk.o
>     LINK     libxdp.so.1.2.0
>     M4       xdp-dispatcher.c
>     CLANG    xdp-dispatcher.o
>     LLC      xdp-dispatcher.o
> llc: xdp-dispatcher.ll:15:54: error: expected ')' at end of argument list
> define dso_local i32 @prog0(%struct.xdp_md* readnone %0) local_unnamed_addr #0 !dbg !47 {
>                                                      ^
> Makefile:134: recipe for target 'xdp-dispatcher.o' failed
> make[2]: *** [xdp-dispatcher.o] Error 1
> Makefile:16: recipe for target 'libxdp' failed
> make[1]: *** [libxdp] Error 2
> Makefile:25: recipe for target 'lib' failed
> make: *** [lib] Error 2
>
> ```
> I tried multiple times from scratch, got the same issue. I am using
> Clang and LLVM version 10, on Ubuntu 18.04.6. What could possible be
> the issue?

Hmm, only think I can think of is maybe a version mismatch between the
clang and llc binaries? What's the contents of your config.mk and the
output of 'clang --version' and 'llc --version'?

**Comment by samy-mohsen** [comment]
@tohojo You were absolutely right. How could I be so dumb. Sorry about that, closing the issue.

**Comment by tohojo** [comment]
Mohamed Samy Mohsen ***@***.***> writes:

> @tohojo You were absolutely right. How could I be so dumb. Sorry about
> that, closing the issue.

Awesome! We should probably check both clang and llc in the configure
script, though, will look into that...
