### ISSUE TITLE
Find better solution for xdp-dump test relying on bpftool

### ISSUE THREAD

**Issue by tohojo** [xdp-project/xdp-tools#150]
A bpftool update broke the xdpdump selftests, and while https://github.com/xdp-project/xdp-tools/commit/6bb0d7103e9674c8bc116e0574385f8381586312 works around the issue, we really should find a better solution since the `--legacy` flag to bpftool may be going away eventually...

**Comment by chaudron** [comment]
@tohojo do you have more details on the specific strict mode causing problems? Also what version of bpftool (distribution) is this, as it has not yet made it into fedora 35.

**Comment by chaudron** [comment]
Quickly tried rawhide but is also to old :(

**Comment by tohojo** [comment]
Eelco Chaudron ***@***.***> writes:

> @tohojo do you have more details on the specific strict mode causing
> problems? Also what version of bpftool (distribution) is this, as it
> has not yet made it into fedora 35.

I think you should be able to trigger it by just compiling the latest
bpftool (there's a github repository now, BTW), and running the selftest
with that without the patch that adds --legacy - strict mode is on by
default on new bpftool versions. I honestly forgot which strict mode bit
it was that caused the failure...

Also, we ran into an issue where the CI testing on our internal
infrastructure failed because bpftool was not available. We only use it
for that particular test, so we don't have an RPM dependency; and adding
one is maybe a bit much just for that. So if we could get rid of bpftool
entirely for the test, that would be awesome; I was contemplating
whether we should expose an option to load programs without the
dispatcher in libxdp (and xdp-loader), but I worry it's a footgun (i.e.,
then we can no longer be sure that an application is compatible if it's
using libxdp)...
