### ISSUE TITLE
Skipping xdpdump tests on unsupported archs

### ISSUE THREAD

**Issue by tohojo** [xdp-project/xdp-tools#162]
The xdpdump tests check for the `bpf_xdp_output_proto` kernel symbol and abort if it is not found. However, on non-x86 architectures, the symbol is there, but xdpdump still doesn't work; so we need a better test.

One option could be to just rely on the skip_if_legacy_fallback test, since multiprog support should mostly coincide with the required xdpdump features (I think?).

See https://bugzilla.redhat.com/show_bug.cgi?id=2032912#c15 and the comments following this for details of the failure.

**Comment by chaudron** [comment]
I will try to get a system with these failures and see if I can make the single program tests pass based on errors. For the multi-program tests, I'll try to skip on unsupported architectures.
