### ISSUE TITLE
xdpdump fails when XDP function BPF-prog names are too long

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-tools#17]
xdpdump fails indicating that it cannot find the eBPF object file, which first of all is a VERY confusing error message, because it is not the real problem.

```
$ sudo ./xdpdump -v -i mlx5p1
Looking for './xdpdump_bpf.o'
Loading bpf file 'xdpdump_bpf.o' from './xdpdump_bpf.o'
ERROR: Can't load eBPF object: No such file or directory(-2)
```

The real problem is that xdpdump identify the function name as ```xdp_tailgrow_fu()```, while the real function name is ```xdp_tailgrow_func4()```. Knowing the kernel, this is because the kernel only stores 15 chars of the original ELF function name (details: in kernel ```struct bpf_prog_aux->name[BPF_OBJ_NAME_LEN]```)

```
$ sudo ./xdpdump -D
if_index  if_name           XDP program entry function
--------  ----------------  --------------------------------------------------
1         lo                <No XDP program loaded!>
[... cut ...]
7         i40e2             <No XDP program loaded!>
8         mlx5p1            xdp_tailgrow_fu()
9         mlx5p2            <No XDP program loaded!>
```

**Workaround:**
Keeping function names (not ```SEC``` section names) below 15 chars in the BPF-prog is a workaround to the issue.

**Help/hints to solve:**
I think the xdpdump program can find the associated full-length name via BTF info. The ```struct bpf_prog_aux``` have a (```const char *```) member named ```attach_func_name```, that I think we can extract somehow (according to comment this is "function name for valid attach_btf_id").

**Comment by netoptimizer** [comment]
Issues with xdpdump can be debugged via supplying ```-vv``` for more verbose.
I provided full output in pastebin here: https://pastebin.com/KzSCvMqM

Important line is:
```
libbpf: xdp_tailgrow_fu is not found in prog's BTF
```

**Comment by tohojo** [comment]
> **Help/hints to solve:**

> I think the xdpdump program can find the associated full-length name
> via BTF info. The ```struct bpf_prog_aux``` have a (```const char
> *```) member named ```attach_func_name```, that I think we can extract
> somehow (according to comment this is "function name for valid
> attach_btf_id").

We don't even need to look at bpf_prog_aux - just get the BTF from the
program from the kernel and iterate that. Functions are stored directly
in the BTF info, e.g. as [7] here:

$ bpftool btf dump file xdp_pass_kern.o
[1] PTR '(anon)' type_id=2
[2] STRUCT 'xdp_md' size=20 vlen=5
	'data' type_id=3 bits_offset=0
	'data_end' type_id=3 bits_offset=32
	'data_meta' type_id=3 bits_offset=64
	'ingress_ifindex' type_id=3 bits_offset=96
	'rx_queue_index' type_id=3 bits_offset=128
[3] TYPEDEF '__u32' type_id=4
[4] INT 'unsigned int' size=4 bits_offset=0 nr_bits=32 encoding=(none)
[5] FUNC_PROTO '(anon)' ret_type_id=6 vlen=1
	'ctx' type_id=1
[6] INT 'int' size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[7] FUNC 'xdp_prog_simple' type_id=5 linkage=global
[8] INT 'char' size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[9] ARRAY '(anon)' type_id=8 index_type_id=10 nr_elems=4
[10] INT '__ARRAY_SIZE_TYPE__' size=4 bits_offset=0 nr_bits=32 encoding
[11] VAR '_license' type_id=9, linkage=global-alloc
[12] DATASEC 'license' size=0 vlen=1
	type_id=11 offset=0 size=4


There's already some code in libxdp.c that iterates the BTF info - see
btf_get_datasec()

**Comment by chaudron** [comment]
Not sure how to extract `attach_func_name` from userspace, as this would be the best option. @netoptimizer any idea without a kernel change? 

@tohojo's idea of using the btf might work, but not if there are two long functions with the same 16 chars. For example:

```
# bpftool btf dump id 1072 | grep xdp_test_prog_w
[7] FUNC 'xdp_test_prog_with_a_long_name' type_id=5
[9] FUNC 'xdp_test_prog_with_a_long_name_too' type_id=8
```

Guess I can still use the BTF info, and drop an error when two long functions with the same name exits.

This will then be solved when I add multiple program support, as there you can enter the full name of the function(s) you would like to trace.
