### ISSUE TITLE
Add `static` or `extern` to header-declared functions in `xsk.h`

### ISSUE THREAD

**Issue by Emanuesson** [xdp-project/xdp-tools#173]
I was switching recently from the libbpf-headers to the libxdp-headers from this repository. I recognized that all the `static`-keywords have been removed from the inline-functions. This makes it impossible to include the header `xdp/xsk.h` mulitple times in any binary without getting linker-warnings about "multiple definitions" of these functions.

The commit-message of the mentioned change (https://github.com/xdp-project/xdp-tools/commit/8ed7e26968445a676fac7b3ced97699390cd6245) states that
> extern inline is used as it's slightly better

However, neither `extern` nor `static` inline was used. Instead the specifier was removed which leads to the situation that the linker complains, if the header is included in several different C-files.

As the header defines structs and functions, it was necessary for me to include it more then once.

I personally propose to simply add `extern` to the function declarations, as this seems to fit the performance-goal and the exported symbols in libxdp best for now.

**Comment by tohojo** [comment]
Ping @kkdwivedi

**Comment by kkdwivedi** [comment]
@Emanuesson Can you draft a small test case showing the problem?

**Comment by kkdwivedi** [comment]
Please give #174 a try, I think the problem is GNU inline semantics.

**Comment by Emanuesson** [comment]
I'm still on it to craft a minimal example. However, I can verify that https://github.com/xdp-project/xdp-tools/pull/174 works to resolve the mentioned problems.

**Comment by kkdwivedi** [comment]
No problem, I was able to reproduce it, it needs to be compiled using -std=gnu89 (or pass -fgnu89-inline for other standards) to hit this.
