### ISSUE TITLE
Unknown opcode 21

### ISSUE THREAD

**Issue by migraichen** [xdp-project/xdp-tools#175]
Hey, 

When crosscompiling xdpdump for ARM 32bit (i.MX7). xdpdump wants to load xdpdump_bpf.o but this generates an "unknown opcode 21" error in the kernel log.

How can we work around this?

Michael

**Comment by tohojo** [comment]
Sadly I think the only workaround is to run it on a different architecture: the required features are not implemented in the ARM JIT.

I think maybe we could detect this and print a better error message - @chaudron WDYT?

**Comment by chaudron** [comment]
@migraichen can you maybe share the -vv output of XDPdump to see if there is anything specific I can trigger a more meaningful full error message on?

**Comment by migraichen** [comment]
@chaudron sure, see below

I did some more research on this one opcode 0x21 seams to be 
BPF_LDX | BPF_W | BPF_ABS but as far as i understand the Kernel source these BPF_LDX/BPF_ABS opcodes are not implemented in any 32bit architecture for the JIT. I have found them in Kernel 4.1 until 4.13 but they got lost by this (https://lwn.net/Articles/723872/) patch. 


`root@arm32:~$ xdpdump -D`
Interface        Prio  Program name      Mode     ID   Tag               Chain actions
lo                     <No XDP program loaded!>
can0                   <No XDP program loaded!>
can1                   <No XDP program loaded!>
eth0                   <No XDP program loaded!>
eth1                   xdp_red_TEST      skb      18   daec8c60a31eae7f 
sit0                   <No XDP program loaded!>

`root@arm32:~$ xdpdump -i eth1 -vv`
Current rlimit 8388608 already >= minimum 1048576
libxdp: DATASEC 'xdp_metadata' not found.
libxdp: DATASEC '.xdp_run_config' not found.
libxdp: Found legacy program with id 18 and 0 component progs
Found func xdp_red_TEST matching xdp_red_TEST
Looking for '//lib/bpf/xdpdump_bpf.o'
Loading bpf file 'xdpdump_bpf.o' from '//lib/bpf/xdpdump_bpf.o'
libbpf: loading //lib/bpf/xdpdump_bpf.o
libbpf: elf: section(3) fentry/func, size 352, link 0, flags 6, type=1
libbpf: sec 'fentry/func': found program 'trace_on_entry' at insn offset 0 (0 bytes), code size 44 insns (352 bytes)
libbpf: elf: section(4) .relfentry/func, size 32, link 26, flags 0, type=9
libbpf: elf: section(5) fexit/func, size 368, link 0, flags 6, type=1
libbpf: sec 'fexit/func': found program 'trace_on_exit' at insn offset 0 (0 bytes), code size 46 insns (368 bytes)
libbpf: elf: section(6) .relfexit/func, size 32, link 26, flags 0, type=9
libbpf: elf: section(7) license, size 4, link 0, flags 3, type=1
libbpf: license of //lib/bpf/xdpdump_bpf.o is GPL
libbpf: elf: section(8) .maps, size 32, link 0, flags 3, type=1
libbpf: elf: section(9) .data, size 12, link 0, flags 3, type=1
libbpf: elf: section(18) .BTF, size 1946, link 0, flags 0, type=1
libbpf: elf: section(20) .BTF.ext, size 1388, link 0, flags 0, type=1
libbpf: elf: section(26) .symtab, size 456, link 1, flags 0, type=2
libbpf: looking for externs among 19 symbols...
libbpf: collected 0 externs total
libbpf: map 'xdpdump_perf_map': at sec_idx 8, offset 0.
libbpf: map 'xdpdump_perf_map': found type = 4.
libbpf: map 'xdpdump_perf_map': found key [2], sz = 4.
libbpf: map 'xdpdump_perf_map': found value [9], sz = 4.
libbpf: map 'xdpdump_perf_map': found max_entries = 256.
libbpf: map 'xdpdump_.data' (global data): at sec_idx 9, offset 0, flags 400.
libbpf: map 1 is "xdpdump_.data"
libbpf: sec '.relfentry/func': collecting relocation for section(3) 'fentry/func'
libbpf: sec '.relfentry/func': relo #0: insn #7 against 'trace_cfg'
libbpf: prog 'trace_on_entry': found data map 1 (xdpdump_.data, sec 9, off 0) for insn 7
libbpf: sec '.relfentry/func': relo #1: insn #38 against 'xdpdump_perf_map'
libbpf: prog 'trace_on_entry': found map 0 (xdpdump_perf_map, sec 8, off 0) for insn #38
libbpf: sec '.relfexit/func': collecting relocation for section(5) 'fexit/func'
libbpf: sec '.relfexit/func': relo #0: insn #8 against 'trace_cfg'
libbpf: prog 'trace_on_exit': found data map 1 (xdpdump_.data, sec 9, off 0) for insn 8
libbpf: sec '.relfexit/func': relo #1: insn #40 against 'xdpdump_perf_map'
libbpf: prog 'trace_on_exit': found map 0 (xdpdump_perf_map, sec 8, off 0) for insn #40
libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux': 0
libbpf: map 'xdpdump_perf_map': created successfully, fd=5
libbpf: map 'xdpdump_.data': created successfully, fd=6
libbpf: sec 'fentry/func': found 10 CO-RE relocations
libbpf: CO-RE relocating [17] struct xdp_buff: found target candidate [2609] struct xdp_buff in [vmlinux]
libbpf: prog 'trace_on_entry': relo #0: kind <byte_off> (0), spec is [17] struct xdp_buff.data (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #0: matching candidate #0 [2609] struct xdp_buff.data (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #0: patched insn #1 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_entry': relo #0: patched insn #1 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_entry': relo #1: kind <byte_off> (0), spec is [17] struct xdp_buff.data_end (0:1 @ offset 8)
libbpf: prog 'trace_on_entry': relo #1: matching candidate #0 [2609] struct xdp_buff.data_end (0:1 @ offset 4)
libbpf: prog 'trace_on_entry': relo #1: patched insn #2 (LDX/ST/STX) off 8 -> 4
libbpf: prog 'trace_on_entry': relo #1: patched insn #2 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_entry': relo #2: kind <byte_off> (0), spec is [17] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_entry': relo #2: matching candidate #0 [2609] struct xdp_buff.rxq (0:4 @ offset 16)
libbpf: prog 'trace_on_entry': relo #2: patched insn #4 (LDX/ST/STX) off 40 -> 16
libbpf: prog 'trace_on_entry': relo #2: patched insn #4 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: CO-RE relocating [21] struct xdp_rxq_info: found target candidate [2607] struct xdp_rxq_info in [vmlinux]
libbpf: prog 'trace_on_entry': relo #3: kind <byte_off> (0), spec is [21] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #3: matching candidate #0 [2607] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #3: patched insn #5 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_entry': relo #3: patched insn #5 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: CO-RE relocating [23] struct net_device: found target candidate [2303] struct net_device in [vmlinux]
libbpf: prog 'trace_on_entry': relo #4: kind <byte_off> (0), spec is [23] struct net_device.ifindex (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #4: matching candidate #0 [2303] struct net_device.ifindex (0:17 @ offset 116)
libbpf: prog 'trace_on_entry': relo #4: patched insn #6 (LDX/ST/STX) off 0 -> 116
libbpf: prog 'trace_on_entry': relo #5: kind <byte_off> (0), spec is [17] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_entry': relo #5: matching candidate #0 [2609] struct xdp_buff.rxq (0:4 @ offset 16)
libbpf: prog 'trace_on_entry': relo #5: patched insn #13 (LDX/ST/STX) off 40 -> 16
libbpf: prog 'trace_on_entry': relo #5: patched insn #13 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_entry': relo #6: kind <byte_off> (0), spec is [21] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #6: matching candidate #0 [2607] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #6: patched insn #15 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_entry': relo #6: patched insn #15 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_entry': relo #7: kind <byte_off> (0), spec is [23] struct net_device.ifindex (0:0 @ offset 0)
libbpf: prog 'trace_on_entry': relo #7: matching candidate #0 [2303] struct net_device.ifindex (0:17 @ offset 116)
libbpf: prog 'trace_on_entry': relo #7: patched insn #16 (LDX/ST/STX) off 0 -> 116
libbpf: prog 'trace_on_entry': relo #8: kind <byte_off> (0), spec is [17] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_entry': relo #8: matching candidate #0 [2609] struct xdp_buff.rxq (0:4 @ offset 16)
libbpf: prog 'trace_on_entry': relo #8: patched insn #23 (LDX/ST/STX) off 40 -> 16
libbpf: prog 'trace_on_entry': relo #8: patched insn #23 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_entry': relo #9: kind <byte_off> (0), spec is [21] struct xdp_rxq_info.queue_index (0:1 @ offset 8)
libbpf: prog 'trace_on_entry': relo #9: matching candidate #0 [2607] struct xdp_rxq_info.queue_index (0:1 @ offset 4)
libbpf: prog 'trace_on_entry': relo #9: patched insn #29 (LDX/ST/STX) off 8 -> 4
libbpf: sec 'fexit/func': found 10 CO-RE relocations
libbpf: prog 'trace_on_exit': relo #0: kind <byte_off> (0), spec is [17] struct xdp_buff.data (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #0: matching candidate #0 [2609] struct xdp_buff.data (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #0: patched insn #2 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_exit': relo #0: patched insn #2 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_exit': relo #1: kind <byte_off> (0), spec is [17] struct xdp_buff.data_end (0:1 @ offset 8)
libbpf: prog 'trace_on_exit': relo #1: matching candidate #0 [2609] struct xdp_buff.data_end (0:1 @ offset 4)
libbpf: prog 'trace_on_exit': relo #1: patched insn #3 (LDX/ST/STX) off 8 -> 4
libbpf: prog 'trace_on_exit': relo #1: patched insn #3 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_exit': relo #2: kind <byte_off> (0), spec is [17] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_exit': relo #2: matching candidate #0 [2609] struct xdp_buff.rxq (0:4 @ offset 16)
libbpf: prog 'trace_on_exit': relo #2: patched insn #5 (LDX/ST/STX) off 40 -> 16
libbpf: prog 'trace_on_exit': relo #2: patched insn #5 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_exit': relo #3: kind <byte_off> (0), spec is [21] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #3: matching candidate #0 [2607] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #3: patched insn #6 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_exit': relo #3: patched insn #6 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_exit': relo #4: kind <byte_off> (0), spec is [23] struct net_device.ifindex (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #4: matching candidate #0 [2303] struct net_device.ifindex (0:17 @ offset 116)
libbpf: prog 'trace_on_exit': relo #4: patched insn #7 (LDX/ST/STX) off 0 -> 116
libbpf: prog 'trace_on_exit': relo #5: kind <byte_off> (0), spec is [17] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_exit': relo #5: matching candidate #0 [2609] struct xdp_buff.rxq (0:4 @ offset 16)
libbpf: prog 'trace_on_exit': relo #5: patched insn #15 (LDX/ST/STX) off 40 -> 16
libbpf: prog 'trace_on_exit': relo #5: patched insn #15 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_exit': relo #6: kind <byte_off> (0), spec is [21] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #6: matching candidate #0 [2607] struct xdp_rxq_info.dev (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #6: patched insn #17 (LDX/ST/STX) off 0 -> 0
libbpf: prog 'trace_on_exit': relo #6: patched insn #17 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_exit': relo #7: kind <byte_off> (0), spec is [23] struct net_device.ifindex (0:0 @ offset 0)
libbpf: prog 'trace_on_exit': relo #7: matching candidate #0 [2303] struct net_device.ifindex (0:17 @ offset 116)
libbpf: prog 'trace_on_exit': relo #7: patched insn #18 (LDX/ST/STX) off 0 -> 116
libbpf: prog 'trace_on_exit': relo #8: kind <byte_off> (0), spec is [17] struct xdp_buff.rxq (0:5 @ offset 40)
libbpf: prog 'trace_on_exit': relo #8: matching candidate #0 [2609] struct xdp_buff.rxq (0:4 @ offset 16)
libbpf: prog 'trace_on_exit': relo #8: patched insn #25 (LDX/ST/STX) off 40 -> 16
libbpf: prog 'trace_on_exit': relo #8: patched insn #25 (LDX/ST/STX) mem_sz 8 -> 4
libbpf: prog 'trace_on_exit': relo #9: kind <byte_off> (0), spec is [21] struct xdp_rxq_info.queue_index (0:1 @ offset 8)
libbpf: prog 'trace_on_exit': relo #9: matching candidate #0 [2607] struct xdp_rxq_info.queue_index (0:1 @ offset 4)
libbpf: prog 'trace_on_exit': relo #9: patched insn #31 (LDX/ST/STX) off 8 -> 4
libbpf: prog 'trace_on_entry': failed to attach: ERROR: strerror_r(-524)=22
ERROR: Can't attach XDP trace fentry function: Unknown error 524

`root@arm32:~$ dmesg | tail`
[   14.884237] IPv6: ADDRCONF(NETDEV_CHANGE): can0: link becomes ready
[   15.098753] Marvell 88E1510 30be0000.ethernet-1:01: attached PHY driver (mii_bus:phy_addr=30be0000.ethernet-1:01, irq=POLL)
[   15.288652] Marvell 88E1510 30be0000.ethernet-1:00: attached PHY driver (mii_bus:phy_addr=30be0000.ethernet-1:00, irq=POLL)
[   16.350820] device eth1 entered promiscuous mode
[   17.208741] fec 30bf0000.ethernet eth1: Link is Up - 100Mbps/Full - flow control off
[   17.208801] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[   21.528616] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   21.529237] fec 30be0000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   35.688218] usb_otg1_vbus: disabling
[  490.598684] unknown opcode 21

**Comment by chaudron** [comment]
> @chaudron sure, see below
> 
> I did some more research on this one opcode 0x21 seems to be BPF_LDX | BPF_W | BPF_ABS but as far as i understand the Kernel source these BPF_LDX/BPF_ABS opcodes are not implemented in any 32bit architecture for the JIT. I have found them in Kernel 4.1 until 4.13 but they got lost by this (https://lwn.net/Articles/723872/) patch.

Thanks @migraichen for the details! One quick question, were you testing with the latest version? Asking as the following commit should give you a more user-friendly error message:

https://github.com/xdp-project/xdp-tools/commit/9c8826e972298a97336bb9af421ebbdbf8fd2210

**Comment by tohojo** [comment]
Assuming this is fixed, so closing...
