### ISSUE TITLE
Error `Couldn't find a BPF file with name xdp-dispatcher.o` when loading XDP

### ISSUE THREAD

**Issue by myl7** [xdp-project/xdp-tools#180]
`sudo xdp-loader load -vv -m native wg0 build/bpf/ingress.o` failed with:

```
<...>
libxdp: DATASEC '.xdp_run_config' not found.
XDP program 0: Run prio: 50. Chain call actions: XDP_PASS
libxdp: Generating multi-prog dispatcher for 1 programs
libxdp: Looking for '/usr/lib/bpf/xdp-dispatcher.o'
libxdp: Couldn't find a BPF file with name xdp-dispatcher.o
libxdp: Couldn't open BPF file 'xdp-dispatcher.o'
Couldn't attach XDP program on iface 'wg0': No such file or directory(-2)
```

<details>
<summary>Full log</summary>

```
Current rlimit 8388608 already >= minimum 1048576
Loading 1 files on interface 'wg0'.
libbpf: loading build/bpf/ingress.o
libbpf: elf: section(3) ingress, size 1744, link 0, flags 6, type=1
libbpf: sec 'ingress': found program 'ingress_f' at insn offset 0 (0 bytes), code size 218 insns (1744 bytes)
libbpf: elf: section(4) license, size 4, link 0, flags 2, type=1
libbpf: license of build/bpf/ingress.o is GPL
libbpf: elf: section(5) .rodata.str1.1, size 81, link 0, flags 32, type=1
libbpf: elf: section(12) .BTF, size 2206, link 0, flags 0, type=1
libbpf: elf: section(14) .BTF.ext, size 1184, link 0, flags 0, type=1
libbpf: elf: section(21) .symtab, size 432, link 1, flags 0, type=2
libbpf: looking for externs among 18 symbols...
libbpf: collected 0 externs total
libbpf: map '.rodata.str1.1' (global data): at sec_idx 5, offset 0, flags 480.
libbpf: map 0 is ".rodata.str1.1"
libbpf: prog 'ingress_f': unrecognized ELF section name 'ingress'
libxdp: DATASEC '.xdp_run_config' not found.
XDP program 0: Run prio: 50. Chain call actions: XDP_PASS
libxdp: Generating multi-prog dispatcher for 1 programs
libxdp: Looking for '/usr/lib/bpf/xdp-dispatcher.o'
libxdp: Couldn't find a BPF file with name xdp-dispatcher.o
libxdp: Couldn't open BPF file 'xdp-dispatcher.o'
Couldn't attach XDP program on iface 'wg0': No such file or directory(-2)
```

</details>

Using iproute2 with `sudo ip link set dev wg0 xdp obj build/bpf/ingress.o sec ingress` works fine though.

Environment:

- xdp-loader: 1.2.3
- libbpf: 0.7.0
- OS: Arch Linux
- Linux: 5.16.16
- LLVM: 13.0.1

My source is available in [myl7/xdptun](https://github.com/myl7/xdptun), if it can help to locate the problem.

**Comment by tohojo** [comment]
How did you install/compile xdp-loader? It needs to either be installed to the system (so the dispatcher file gets put into /usr/lib/bpf), or you need to enable static linking (in which case the file should be embedded).

Also, no that you can't run XDP in native mode on wireguard; `ip` will fall back to generic XDP which is why that works; but do note that wireguard is layer-3, so there won't be an ethernet header (which means you can't re-use XDP programs between wireguard and other interfaces). See https://lore.kernel.org/r/20200815074102.5357-1-Jason@zx2c4.com for an extensive discussion of why this is, and why it's not likely to change...

**Comment by cloftus** [comment]
I encountered this issue when the files were put into /usr/local/lib64/bpf/ on my machine. Is this the case for you too?
Does it work if you create a symlink to the missing file in /usr/lib/bpf or /usr/local/lib/bpf?
Or you could try set the environment variable LIBXDP_OBJECT_PATH=/usr/local/lib64/bpf/
The code where the file is searched for is here: https://github.com/xdp-project/xdp-tools/blob/v1.2.2/lib/libxdp/libxdp.c#L1066
XDP_OBJECT_ENVVAR is defined as LIBXDP_OBJECT_PATH in libxdp.h

**Comment by myl7** [comment]
> How did you install/compile xdp-loader?

Since I am using Arch Linux, I installed it via AUR [xdp-tools](https://aur.archlinux.org/packages/xdp-tools) package, which has recent updates and according to the `PKGBUILD`, it should be installed system-wide.

<details>
<summary>All files installed from the package</summary>

```
xdp-tools /usr/
xdp-tools /usr/bin/
xdp-tools /usr/bin/xdp-filter
xdp-tools /usr/bin/xdp-loader
xdp-tools /usr/bin/xdpdump
xdp-tools /usr/include/
xdp-tools /usr/include/xdp/
xdp-tools /usr/include/xdp/libxdp.h
xdp-tools /usr/include/xdp/parsing_helpers.h
xdp-tools /usr/include/xdp/prog_dispatcher.h
xdp-tools /usr/include/xdp/xdp_helpers.h
xdp-tools /usr/include/xdp/xdp_stats_kern.h
xdp-tools /usr/include/xdp/xdp_stats_kern_user.h
xdp-tools /usr/include/xdp/xsk.h
xdp-tools /usr/lib/
xdp-tools /usr/lib/libxdp.so
xdp-tools /usr/lib/libxdp.so.1
xdp-tools /usr/lib/libxdp.so.1.2.0
xdp-tools /usr/lib/pkgconfig/
xdp-tools /usr/lib/pkgconfig/libxdp.pc
xdp-tools /usr/share/
xdp-tools /usr/share/man/
xdp-tools /usr/share/man/man3/
xdp-tools /usr/share/man/man3/libxdp.3.gz
xdp-tools /usr/share/man/man8/
xdp-tools /usr/share/man/man8/xdp-filter.8.gz
xdp-tools /usr/share/man/man8/xdp-loader.8.gz
xdp-tools /usr/share/man/man8/xdpdump.8.gz
```

</details>

And sincerely thanks for your explanations about WireGuard! As WireGuard is one of the tests it should save lots of my work from wired things.

But even when I use an ordinary interface like `wlp1s0` I can only still get the same error.

**Comment by myl7** [comment]
> I encountered this issue when the files were put into /usr/local/lib64/bpf/ on my machine. Is this the case for you too?

No. The files on my device lies in `/usr/lib/bpf`.

**Comment by tohojo** [comment]
myl7 ***@***.***> writes:

>> How did you install/compile xdp-loader?
>
> Since I am using Arch Linux, I installed it via AUR
> [xdp-tools](https://aur.archlinux.org/packages/xdp-tools) package,
> which has recent updates and according to the `PKGBUILD`, it should be
> installed system-wide.

Ah, that PKGBUILD is broken, unfortunately. I left a comment on AUR; in
the meantime, if you want to fix it, you can get rid of this line in the
PKGBUILD and recompile:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xdp-tools#n37

**Comment by myl7** [comment]
Many thanks! It works now!

**Comment by LinArcX** [comment]
i have the same problem. can i ask where i should put `xdp-dispatcher.o` in my system?

**Comment by myl7** [comment]
> where i should put `xdp-dispatcher.o` in my system?

Though `xdp-dispatcher.o` is not part of the package `xdp-tools` I installed at that time,
I do have the file at `/usr/lib/bpf/xdp-dispatcher.o`.

So if you can find files like `/usr/lib/bpf/xdp*.o` (or `/usr/local/lib*/bpf/xdp*.o` as given above), you can try putting it in the same directory with these `xdp*.o` files.
