### ISSUE TITLE
Deny all and specifying filtered (allowed) ports doesn't work

### ISSUE THREAD

**Issue by darkblaze69** [xdp-project/xdp-tools#181]
Trying to deny all tcp except some ports.

Debian 11, kernel 5.10.103-1
Intel Corporation I210 Gigabit Network Connection (igb kernel module)
xdp-filter load enp4s0 -p deny -f tcp
xdp-filter port -p tcp -m src,dst 443
xdp-filter port -p tcp -m src,dst 80

For the first couple of tries it allows connections, but then it doesn't connect though increases hit counter and pass counter.

I tried v1.2.3 and the latest dev.

**Comment by tohojo** [comment]
darkblaze69 ***@***.***> writes:

> Trying to deny all tcp except some ports.
>
> Debian 11, kernel 5.10.103-1
> Intel Corporation I210 Gigabit Network Connection (igb kernel module)
> xdp-filter load enp4s0 -p deny -f tcp
> xdp-filter port -p tcp -m src,dst 443
> xdp-filter port -p tcp -m src,dst 80
>
> For the first couple of tries it allows connections, but then it
> doesn't connect though increases hit counter and pass counter.

Huh, that's odd; do you see that packets on the host (with tcpdump) at all?

**Comment by darkblaze69** [comment]
yes, I see syn packets, but no acks etc.

**Comment by tohojo** [comment]
darkblaze69 ***@***.***> writes:

> yes, I see syn packets, but no acks etc.

Are you running xdp-filter on the client or server side of the connection?

**Comment by darkblaze69** [comment]
A bit complicated setup.
It runs on the server side (KVM host), so on this KVM host I see syn packets from client.
NIC acts as a Linux bridge for KVM virtual machine and it's virtio nic. On the host no IP set up. IP presents only on the VM.
Though as I said it allowed first 1-10 connections to pass after allowing specific ports in xdp-filter and then only SYNs from client are seen.

**Comment by tohojo** [comment]
darkblaze69 ***@***.***> writes:

> A bit complicated setup.
> It runs on the server side (KVM host), so on this KVM host I see syn packets from client.
> NIC acts as a Linux bridge for KVM virtual machine and it's virtio nic. On the host no IP set up. IP presents only on the VM.
> Though as I said it allowed first 1-10 connections to pass after
> allowing specific ports in xdp-filter and then only SYNs from client
> are seen.

Right, okay, well from that description XDP is not involved at all in
the return path, so I very much doubt this is a bug in xdp-filter :)

**Comment by darkblaze69** [comment]
ok closing it
