### ISSUE TITLE
how to capture AF_XDP Tx and Rx packets

### ISSUE THREAD

**Issue by shuiouyfm** [xdp-project/xdp-tools#192]
hi，I tried to capture the AF_XDP both Tx and Rx packets to a file, but seems only Rx packets are collected. How to capute the Tx direct packet？ is there any solution  or roadmap for it?

**Comment by tohojo** [comment]
shuiouyfm ***@***.***> writes:

> hi，I tried to capture the AF_XDP both Tx and Rx packets to a file,
> but seems only Rx packets are collected. How to capute the Tx direct
> packet？ is there any solution  or roadmap for it?

Yeah, there's no XDP TX hook. It's on the wishlist, but no time frame...
