### ISSUE TITLE
bpf limit

### ISSUE THREAD

**Issue by andrewxdd1** [xdp-project/xdp-tools#194]
Hello

Is there any patch or something regarding the bpf jump limit as far i know is limited to 100 ?

How can i bypass that

**Comment by andrewxdd1** [comment]
> andrew ***@***.***> writes:
> Hello Is there any patch or something regarding the bpf jump limit as far i know is limited to 100 ?
> What jump limit are you referring to, exactly?

Hello i speak about this

BPF's max jump limit within the while loop

**Comment by tohojo** [comment]
andrew ***@***.***> writes:

>> andrew ***@***.***> writes:
>> Hello Is there any patch or something regarding the bpf jump limit as far i know is limited to 100 ?
>> What jump limit are you referring to, exactly?
>
> Hello i speak about this
>
> BPF's max jump limit within the while loop

Erm, write a simpler while loop? :)

There's also the (fairly new) bpf_loop() helper which can run a function
callback as a loop...
