### ISSUE TITLE
xdp loader

### ISSUE THREAD

**Issue by andrewxdd1** [xdp-project/xdp-tools#195]
Hello

Is it possible to load xdp native mode on bond interfaces?

I tried on vlan interfaces but seems doesn't work

My network card supports xdp native if i load it on the normal interfaces work but i want to use both ports and loading 1 program per interface is not a solution as i want to use the full power of the port

**Comment by tohojo** [comment]
andrew ***@***.***> writes:

> Hello
>
> Is it possible to load xdp native mode on bond interfaces?
>
> I tried on vlan interfaces but seems doesn't work
>
> My network card supports xdp native if i load it on the normal
> interfaces work but i want to use both ports and loading 1 program per
> interface is not a solution as i want to use the full power of the
> port

XDP support for the bonding driver was added in upstream commit:
9e2ee5c7e7c3 ("net, bonding: Add XDP support to the bonding driver")
which was part of the 5.15 kernel release...

**Comment by andrewxdd1** [comment]
> andrew ***@***.***> writes:
> Hello Is it possible to load xdp native mode on bond interfaces? I tried on vlan interfaces but seems doesn't work My network card supports xdp native if i load it on the normal interfaces work but i want to use both ports and loading 1 program per interface is not a solution as i want to use the full power of the port
> XDP support for the bonding driver was added in upstream commit: 9e2ee5c7e7c3 ("net, bonding: Add XDP support to the bonding driver") which was part of the 5.15 kernel release...

Intresting sounds good

Thank you!
