### ISSUE TITLE
xdp.frags support for libxdp

### ISSUE THREAD

**Issue by jcherrykr** [xdp-project/xdp-tools#235]
I'm thinking this Atlantic is supposed to support this section. Perhaps somehow I'm wrong, and someone can point out why, but this seems like some issue, so posting it.

My kernel program will not load unless the MTU is around 3000. When set to 9000 it gives this error. Unless we have some kind of misunderstanding on my team, the nic should be giving us chained buffers.
`libxdp: Released lock fd 17
libxdp: Replacing XDP fd -1 with 8 on ifindex 2
libbpf: Kernel error message: atlantic: prog does not support XDP frags
libxdp: Error attaching XDP program to ifindex 2: Operation not supported
libxdp: XDP mode not supported; try using SKB mode
libxdp: Failed to attach dispatcher on ifindex 2: Operation not supported
libxdp: Acquired lock from /sys/fs/bpf/xdp with fd 17
`

SEC("xdp.frags")

I did notice that setting to a single did not work, but don't think this is related. Including for completeness:
sudo ethtool -L enp10s0 combined 1
netlink error: Operation not supported

**Comment by tohojo** [comment]
This happens because libxdp doesn't support frags. We should fix this; moved the issue to the xdp-tools repository to track this...
