### ISSUE TITLE
possible to provide installation instructions for ubuntu 22.04?

### ISSUE THREAD

**Issue by ultperf** [xdp-project/xdp-tools#247]
possible to provide installation instructions for ubuntu 22.04?

can i buy a coffee for this? truly impossible to find any references of sort for this. cannot believe so unpopular.

**Comment by tohojo** [comment]
ultperf ***@***.***> writes:

> possible to provide instructions for ubuntu 22.04

Instructions for what? What problem are you having, exactly?

**Comment by ultperf** [comment]
@tohojo thx for helping out. i will provide the installation instructions here for ubuntu 22.04 for future users.

it's not very evident how to use xdp-tools really. thx in advance.
