### ISSUE TITLE
saw inside xdp-filter.c, what's NEED_RLIMIT about?

### ISSUE THREAD

**Issue by hiqsociety** [xdp-project/xdp-tools#249]
saw inside xdp-filter.c, what's NEED_RLIMIT about?

is it the total overall size limit of usable ram for BPF_CPU_HASH... etc?

```
./xdp-filter.c:26:#define NEED_RLIMIT (20 * 1024 * 1024) /* 10 Mbyte */
```

**Comment by tohojo** [comment]
It's the minimum value for `ulimit -l` that xdp-filter will set before running...

**Comment by hiqsociety** [comment]
@tohojo ok thx
