### ISSUE TITLE
Map key size mismatch when using xdp-loader.

### ISSUE THREAD

**Issue by stevelorenz** [xdp-project/xdp-tools#25]
Dear developers of xdp-tools,

Thanks so much for your great effort! I am a PhD student and want to implement something using XDP. Therefore, I successfully set up the development environment using xdp-tool and started to follow xdp-tutorial. I mainly want to use the `xdp-loader` provided by xdp-tool to make loading/unloading stuff easier. When tried [basic04](https://github.com/xdp-project/xdp-tutorial/tree/master/basic04-pinning-maps) in xdp-tutorial, the `xdp-loader` does not work properly in pinning the map.

I run following command to load the XDP program on lo interface with a given pin path. It works fine without error (I have checked with `xdp-loader status`).
```bash
xdp-loader load -m skb -p /sys/fs/bpf lo ./xdp_prog_kern.o
```
Then I can see the map file in `/sys/fs/bpf/programs/lo/xdp_pass`. Then I modified the [xdp-stats.c](https://github.com/xdp-project/xdp-tutorial/blob/master/basic04-pinning-maps/xdp_stats.c) to use `/sys/fs/bpf/programs` as `pin_dir` and `xdp_pass` as the map name. Then I recompile the `xdp_stats` and run it with following command:
```bash
./xdp_stats --dev lo
```
It shows the following error:
```bash
ERR: check_map_fd_info() Map key size(-677305523) mismatch expected size(4)
ERR: map via FD not compatible 
```
So the user space program can find the map file but the key size is wrong when calling `check_map_fd_info`. This example works fine when I use the [xdp_loader.c](https://github.com/xdp-project/xdp-tutorial/blob/master/basic04-pinning-maps/xdp_loader.c) instead of the `xdp-loader` utility provided by the xdp-tools(`xdp_loader.c` pins the maps in `/sys/fs/bpf/lo/xdp_stats_map`).

Am I doing something wrong here? Could you please give me some hints? Thanks so much for your help.

- xdp-tool version: release: 0.0.3
- xdp-tutorial version: master:b13cfb8e6bef6c85017bb1ffdf6f2922a87fdb21

**Comment by tohojo** [comment]
Yeah, xdp-tools assumes somewhat newer versions of most of the BPF infrastructure than the tutorial currently does, so these two are not quite compatible, I'm afraid. The map pinning issue just came up over on xdp-tutorial, actually; see https://github.com/xdp-project/xdp-tutorial/issues/125

**Comment by stevelorenz** [comment]
Thanks so much for your response. :smile:  I didn't know about this issue. So I will now firstly finish the tutorial using the infrastructure provided in xdp-tutorial. And look at xdp-tools's implementation when I finish the tutorial (So after becoming a XDP advanced newbie :wink: ).

**Comment by tohojo** [comment]
Zuo Xiang <notifications@github.com> writes:

> Thanks so much for your response. :smile:  I didn't know about this
> issue. So I will now firstly finish the tutorial using the
> infrastructure provided in xdp-tutorial. And look at xdp-tools's
> implementation when I finish the tutorial (So after becoming a XDP
> advanced newbie :wink: ).

Sounds like a plan :)
