### ISSUE TITLE
Loading of XDP program fails with `missing BPF prog type, check ELF section name 'xdp/dispatcher'`

### ISSUE THREAD

**Issue by fnordahl** [xdp-project/xdp-tools#254]
The Open vSwitch project makes use of libbpf and libxdp to enable use of AF_XDP.

If Open vSwitch is compiled with libbpf 0.8 (which corresponds to libpf from a 5.19 kernel) it works OK.

If it is compiled with a more recent libbpf, attaching the XDP program fails with:
```
libbpf: prog 'xdp_dispatcher': missing BPF prog type, check ELF section name 'xdp/dispatcher'
libbpf: prog 'xdp_dispatcher': failed to load: -22
```

I suspect xdp-tools need an update similar to [0] after [1].

0: https://lore.kernel.org/lkml/tencent_7DD02046A8398BE3324F85E0F56ED41EB105@qq.com/T/
1: https://github.com/torvalds/linux/commit/450b167fb9be91a8164d3f3d734674f5fe95b22d

cc @igsilya

**Comment by tohojo** [comment]
Which version of libxdp are you using? This has already been fixed in
commit:

d1651180165a ("libxdp: Convert xdp-dispatcher to use strict section name")

**Comment by hiqsociety** [comment]
@fnordahl i think u need to copy everything *.o  <- generated when u run together too.

**Comment by fnordahl** [comment]
Thank you for the pointer @tohojo, building with xdp-tools from tip of master does indeed work.

The commit does not appear to be part of any xdp-tools tag/release and the last release is a few years old, is a new release planned anytime soon?

**Comment by tohojo** [comment]
Frode Nordahl ***@***.***> writes:

> Thank you for the pointer @tohojo, building with xdp-tools from tip of master does indeed work.

Great!

> The commit does not appear to be part of any xdp-tools tag/release and
> the last release is a few years old, is a new release planned anytime
> soon?

Yeah, I backported it to the 1.2 branch and will tag a new release as
soon as I'm done with https://github.com/xdp-project/xdp-tools/pull/158

**Comment by tohojo** [comment]
This is now included in v1.2.9

**Comment by fnordahl** [comment]
Thank you for the quick turnaround @tohojo, much appreciated! We'll make sure those bits get out there

**Comment by tohojo** [comment]
Great! You're welcome :)
