### ISSUE TITLE
*** ERROR: Cannot find tool bpftool, when using ubuntu 22.04 installing on new server

### ISSUE THREAD

**Issue by ultperf** [xdp-project/xdp-tools#258]
hi @tohojo,
```
FORCE_SUBDIR_LIBBPF=1 ./configure
*** ERROR: Cannot find tool bpftool
```
how do i resolve this? got this problem with new vps installation. not sure what's the issue with bpftool
did plenty of apt-get etc not sure where to start

**Comment by ultperf** [comment]
apt install linux-tools-common

**Comment by tohojo** [comment]
ultperf ***@***.***> writes:

> hi @tohojo,
> ```
> FORCE_SUBDIR_LIBBPF=1 ./configure
> *** ERROR: Cannot find tool bpftool
> ```
> how do i resolve this? got this problem with new vps installation. not
> sure what's the issue with bpftool

The issue with bpftool is that it's not there :)

This was a new dependency just added today when merging
https://github.com/xdp-project/xdp-tools/pull/158 - you'll need to
either install it or use the 'v1.2' branch...
