### ISSUE TITLE
error "bpftool doesn't support skeleton generation", with installation of xdp-tools

### ISSUE THREAD

**Issue by ultperf** [xdp-project/xdp-tools#260]
@tohojo how to resolve issues below?
```
root@test:/usr/local/src/xdp-tools# ./configure
Found clang binary 'clang' with version 14 (from 'Ubuntu clang version 14.0.0-1ubuntu1')
bpftool doesn't support skeleton generation
```
pls help resolve this thx

**Comment by ultperf** [comment]
resolved with 
"apt install linux-tools-common linux-tools-generic"

**Comment by tohojo** [comment]
ultperf ***@***.***> writes:

> how to resolve issues below?
> ```
> ***@***.***:/usr/local/src/xdp-tools# ./configure
> Found clang binary 'clang' with version 14 (from 'Ubuntu clang version 14.0.0-1ubuntu1')
> bpftool doesn't support skeleton generation
> ```

That's because the version of bpftool is too old...
