### ISSUE TITLE
Buffering mechanism

### ISSUE THREAD

**Issue by KillianCdP** [xdp-project/xdp-tools#263]
Hi,

I am doing some latency tests using an AF_XDP emitter, receiver and forwarder (really close to the previous `xdpsock` example from the kernel, now found in part in `xdp-bench`) between two hosts.  
I am sending packets one by one at various intervals, and I've noticed that the smaller the packet interval the lower the per packet latency, which seems odd to me. 
I am sending packets one at a time, interval ranging from 1000 ms to 1 ms.

Therefore it seems there is a buffering mechanism somewhere but I don't see where it could happen, is this somehow related to AF_XDP ?

Thank you

**Comment by tohojo** [comment]
With those intervals you are definitely not stressing hardware. Longer
latencies can stem from a couple of reasons:

- When there's longer between packets, the kernel exits the NAPI poll
  cycle earlier, so the next packet that comes in has to generate an
  interrupt which adds latency.

- When the system is idle, the CPU can have time to go into a lower
  power state and has to wake back up before it can service an incoming
  packet.


With the time scales you state, my guess would be the second effect (CPU
power saving)...

**Comment by KillianCdP** [comment]
Sorry for the late reply!

Indeed it seems that playing with the CPU C State has a big impact on that, thanks for the tip!
