### ISSUE TITLE
Does the xdp-dump use system time or adapter_unsynced (Adapter, not synced with system time) for the timestamp?

### ISSUE THREAD

**Issue by arukshani** [xdp-project/xdp-tools#275]
Hi,

Does the xdp-dump use system time or the timestamp provided by the network adapter?

Thanks!

**Comment by tohojo** [comment]
System time. Specifically, the timestamp added by the kernel to the perf event when dumping a packet to userspace...

**Comment by arukshani** [comment]
Thank you for the clarification.
