### ISSUE TITLE
xdp-dump: Use perf-ring bulking to speedup performance

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-tools#28]
The [current xdp-dump implementation](https://github.com/xdp-project/xdp-tools/blob/master/xdp-dump/xdpdump.c#L569) is not taking advantage of "bulking" through the perf-ring buffer, instead it will get wakeup for each packet. I have measured *significant* performance improvements when enabling this.

In `struct perf_event_attr` the member `wakeup_events` specify getting an fd notification for X events.

Example see: https://github.com/netoptimizer/prototype-kernel/blob/master/kernel/samples/bpf/xdp_tcpdump_user.c#L236-L238

The example from [prototype-kernel](https://github.com/netoptimizer/prototype-kernel/blob/master/kernel/samples/bpf/xdp_tcpdump_user.c#L236-L238) is not complete, because it does not handle flushing/consuming frames on exit. It is actually disabled in the code, as it was loosing packets on exit.

**Comment by netoptimizer** [comment]
Maybe @olsajiri or @acmel can help us with the C-code API for flushing/emptying the perf-ring buffer on exit?

**Comment by acmel** [comment]
Em Mon, May 25, 2020 at 05:06:28AM -0700, Jesper Dangaard Brouer escreveu:
> Maybe @olsajiri or @acmel can help us with the C-code API for flushing/emptying the perf-ring buffer on exit?

Have you looked at:

  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/lib/perf/Documentation/examples/sampling.c

Its part of libperf, Jiri even added documentation at:

  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/lib/perf/Documentation/

perf itself can be used as an example on using it, with
'tools/perf/builtin-record.c' just consuming the buffers as fast as
possible to dump it into a perf.data file, while 'builtin-top.c' and
'builtin-trace.c' will parse the events and act on them as they are read
from the mmap ring buffer.

- Arnaldo
 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/xdp-project/xdp-tools/issues/28#issuecomment-633539883

-- 

- Arnaldo

**Comment by chaudron** [comment]
@acmel thanks for adding the above, I did not notice it until I sort of solved it for my implementation.

xdpdump is using libbpf's perf_buffer__xxx() APIs for doing this, which does not use the libperf. To keep using this API I'll will sent a patch upstream to just flush/process the buffers without waiting for a poll wake up.

**Comment by olsajiri** [comment]
from quick look I did not see ring buffer  'flush' interface in libbpf perf buffer API,
you might need to add it.. or switch to libperf ;-)

**Comment by chaudron** [comment]
> from quick look I did not see ring buffer 'flush' interface in libbpf perf buffer API,
> you might need to add it.. or switch to libperf ;-)

Just did https://lore.kernel.org/bpf/159048487929.89441.7465713173442594608.stgit@ebuild/T/#u  
maybe we can switch later...

**Comment by tohojo** [comment]
Let's have this depend on #42 for backwards compatibility
