### ISSUE TITLE
Handle makefile rebuild when updating libbpf submodule

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-tools#29]
Issue: After running `git submodule update` the xdp-tools Makefile system does not detect that it needs to rebuild libbpf.

**The full sequence of commands below**

First `make` command compile everything, and warns me that I should run `git submodule update`:
```
$ make

** WARNING **: git submodule SHA-1 out-of-sync
 consider running: git submodule update


lib

  util
    CC       params.o
    CC       logging.o
    CC       util.o
    CC       stats.o

  libxdp
    CC       staticobjs/libxdp.o
    LINK     libxdp.a
    CC       sharedobjs/libxdp.o
    LINK     libxdp.so.0.0.3
    M4       xdp-dispatcher.c
    CLANG    xdp-dispatcher.o
    LLC      xdp-dispatcher.o

xdp-filter
[... cut ...]

xdp-loader
make[2]: Nothing to be done for 'all'.
    CC       xdp-loader
    LINK     xdp-dispatcher.o

xdp-dump
make[2]: Nothing to be done for 'all'.
    CC       xdpdump
    CLANG    xdpdump_bpf.o
    LLC      xdpdump_bpf.o
    LINK     xdp-dispatcher.o
```

Next I run `git submodule update` which finds a new libbpf version:
```
$ git submodule update
Submodule path 'lib/libbpf': checked out '3b239425426e4fa1c204ea3c708d36ec3f509702'
```

Then I run `make` to get everything compile against the new libbpf, but that does not happen:
```
$ make

lib

  util
make[2]: Nothing to be done for 'all'.

  libxdp
make[2]: Nothing to be done for 'all'.

xdp-filter
make[2]: Nothing to be done for 'all'.

xdp-loader
make[2]: Nothing to be done for 'all'.

xdp-dump
make[2]: Nothing to be done for 'all'.
```

**Comment by tohojo** [comment]
Yeah, a 'make clean' is generally needed to pick that change up. Not
sure if there's a good way to detect this situation from the Makefile?
I'm also considering just replacing the libbpf submodule with a manual
copy of all the source files, since the submodule keeps bringing up
problems like this - thoughts?

**Comment by netoptimizer** [comment]
I'll try to fix it up.
