### ISSUE TITLE
xdp-loader/xdp-filter can't unload generic/offloaded XDP programs

### ISSUE THREAD

**Issue by aspsk** [xdp-project/xdp-tools#3]
The `xdp-loader` and `xdp-filter` programs have an option `-S` for `load` command to attach XDP programs in SKB mode, however, no such option is provided for the `unload` command. Besides that, no option is provided to load/unload programs in HW offload mode.

I think that the `-S` option should be replaced with `-M mode` option to choose between `xdp`, `xdpgeneric`, and `xdpoffload`. (Tried to implement this fast, but was confused in how options are parsed ;) Probably will have time to do this next week if not be fixed before.)

**Comment by tohojo** [comment]
Funny you should open this now, I'm sitting with Jesper talking about this right this minute. And yeah, this should be fixed; not sure about -M; we want to default to native mode, as silent fallback to skb-mode is a support issue...

**Comment by aspsk** [comment]
The `-M` option let's us to choose between more than two modes. I agree that `native` should be the default

**Comment by tohojo** [comment]
Hmm, yeah, I guess a -M with a default could work...

**Comment by tohojo** [comment]
Hmm, yeah, I guess a -M with a default could work...
