### ISSUE TITLE
Odd warning from check_abi: Warning: Num of global symbols in libxdp.o xsk.o (68) does NOT match with num of versioned symbols in libxdp.so (71)

### ISSUE THREAD

**Issue by hhoffstaette** [xdp-project/xdp-tools#302]
After getting 1.3.1 to build properly (thanks!) the Gentoo CI promptly found .. "something", but we're not really sure what causes it.
The report is here (with log attached): https://bugs.gentoo.org/899742

As stated in the bug I cannot recreate this at all when building myself - I get no warnings from ar creating the libxdp archive, using the same toolchain options, binutils, elfutils etc.
Any idea what might be responsible for the ar warnings from the check_abi target?

**Comment by tohojo** [comment]
Holger Hoffstätte ***@***.***> writes:

> After getting 1.3.1 building properly (thanks!) our CI promptly found .. "something", but we're not really sure what it is.
> The report is here (with log attached): https://bugs.gentoo.org/899742
>
> As stated in the bug I cannot recreate this at all when building myself - I get no warnings from ar creating the libxdp archive, using the same toolchain options, binutils, elfutils etc.
> Any idea what might be responsible for the ar warnings from the check_abi target?

The libxdp Makefile contains this check. My guess would be that maybe
the CI system is missing one of the utilities used to compute those
numbers, most likely 'readelf'? They're defined as:

GLOBAL_SYM_COUNT = $(shell readelf -s --wide $(XDP_IN_SHARED) | \
			   cut -d "@" -f1 | sed 's/_v[0-9]_[0-9]_[0-9].*//' | \
			   sed 's/\[.*\]//' | \
			   awk '/GLOBAL/ && /DEFAULT/ && !/UND/ {print $$NF}' | \
			   sort -u | wc -l)
VERSIONED_SYM_COUNT = $(shell readelf --dyn-syms --wide $(OBJDIR)/libxdp.so | \
			      grep -Eo '[^ ***@***.***_' | cut -d@ -f1 | sort -u | wc -l)

**Comment by hhoffstaette** [comment]
Thanks for the idea, but a missing readelf seems unlikely since it's part of binutils and the CI has the same version as I do (and I can build & use everything just fine). So it seems there's definitely something off in the CI - we'll keep looking.

**Comment by hhoffstaette** [comment]
I'm closing this for now since it's _likely_ caused by some Gentoo toolchain issues, since we support multiple installed gcc and llvm/clang versions and it looks likely someone somehow crossed their streams. If and when we figure out what exactly (if anything) is wrong in xdp-tools we can open a separate PR for the fix.
