### ISSUE TITLE
libxdp: Can't fall back to legacy load with 2 programs

### ISSUE THREAD

**Issue by zhouushaooqiann** [xdp-project/xdp-tools#307]
Hi, I tried to use xdp-loader to load 2 native XDP programs on the same network interface, but getting below error:

```
 libxdp: Can't fall back to legacy load with 2 programs
This means that the kernel does not support the features needed
by the multiprog dispatcher, either because it is too old entirely,
or because it is not yet supported on the current architecture.

Attaching XDP program in native mode not supported - try SKB mode.
```
I then tried SKB mode, which yielded the same error.

I'm using Ubuntu 22.04 HWE with 5.19.0-37-generic arm64

Any help or discussion is appreciated!

**Comment by tohojo** [comment]
jackyzhou ***@***.***> writes:

> Hi, I tried to load 2 XDP programs on the same network interface, but getting below error:
>
> ```
>  libxdp: Can't fall back to legacy load with 2 programs
> This means that the kernel does not support the features needed
> by the multiprog dispatcher, either because it is too old entirely,
> or because it is not yet supported on the current architecture.
>
> ```
> I'm using Ubuntu 22.04 HWE with 5.19.0-37-generic arm64
>
> Any help or discussion is appreciated!

As the error message says: This is not supported by the kernel on ARM.
There's ongoing work to add this support, but it hasn't landed yet...
