### ISSUE TITLE
xdp-dump: Attach own XDP prog for dumping packets

### ISSUE THREAD

**Issue by netoptimizer** [xdp-project/xdp-tools#31]
I found it very confusing that a program named `xdpdump` will use the `tcpdump` hook to dump packets, when there isn't any other XDP-prog already attached on the interfaces.

I do like that the `xdpdump` program warns the end-user about this behaviour:

```
$ sudo ./xdpdump -i mlx5p1
WARNING: Specified interface does not have an XDP program loaded, capturing
         in legacy mode!
```

I think xdpdump should at-least have an option to load it's own XDP program that does the dumping (via perf-ring and returns XDP_PASS).  An an end-user, I want to "see" packets and timestamps at XDP-layer. (If I wanted to see it at tcpdump hook, I would use `tcpdump` instead. I don't see a reason for xdpdump to replicated what tcpdump tools already does).

**Comment by chaudron** [comment]
We had various discussions around this, mainly related to customer support, and thinks that would happen to the kernel if you add your own program.

I will add an item to my TODO list to add an option that will load a dummy program.

**Comment by netoptimizer** [comment]
> @chaudron:
> I will add an item to my TODO list to add an option that will load a dummy program.

I don't like the idea of loading a dummy program, and then attaching to that dummy prog.

My proposal is to load a real [XDP program](https://github.com/xdp-project/xdp-tutorial/blob/master/tracing04-xdp-tcpdump/xdp_sample_pkts_kern.c) that does the write into perf-ring (`bpf_perf_event_output`).

The reason is that this will be much faster than `tcpdump` (that is after you also fix #28).

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

>> @chaudron:
>> I will add an item to my TODO list to add an option that will load a dummy program.
>
> I don't like the idea of loading a dummy program, and then attaching
> to that dummy prog.
>
> My proposal is to load a real [XDP
> program](https://github.com/xdp-project/xdp-tutorial/blob/master/tracing04-xdp-tcpdump/xdp_sample_pkts_kern.c)
> that does the write into perf-ring (`bpf_perf_event_output`).

If we are going to add support for loading an XDP program (no matter
which kind), we should be sure to carefully document what side effects
that has on the traffic. I.e., on which drivers can you do this without
causing drops while the interface is reconfiguring itself to run XDP,
and on which can't you? People are probably going to run this in
production, so we should be clear about any side effects... :)

> The reason is that this will be much faster than `tcpdump` (that is
> after you also fix #28).

If the goal is a faster tcpdump, wouldn't it make sense to get the
support into tcpdump itself?

**Comment by netoptimizer** [comment]
Added this to milestone, because this behavior should be resolved in first release of the tool.

**Comment by netoptimizer** [comment]
> Jesper Dangaard Brouer <notifications@github.com> writes:
> > @chaudron: > I will add an item to my TODO list to add an option that will load a dummy program. I don't like the idea of loading a dummy program, and then attaching to that dummy prog. My proposal is to load a real [XDP program](https://github.com/xdp-project/xdp-tutorial/blob/master/tracing04-xdp-tcpdump/xdp_sample_pkts_kern.c) that does the write into perf-ring (`bpf_perf_event_output`).
> >
> (@tohojo ) If we are going to add support for loading an XDP program (no matter which kind), we should be sure to carefully document what side effects that has on the traffic. I.e., on which drivers can you do this without causing drops while the interface is reconfiguring itself to run XDP, and on which can't you? People are probably going to run this in production, so we should be clear about any side effects... :)

Sure, we should document the side-effect (which is a general XDP property), but I think the name of the program `xdpdump` very clearly indicate that this will activate XDP.

> (@netoptimizer)The reason is that this will be much faster than `tcpdump` (that is after you also fix #28).
>> (@tohojo  If the goal is a faster tcpdump, wouldn't it make sense to get the support into tcpdump itself?

Definitely not on default, due to above side-effect (mostly TSO disable side effect). Plus tcpdump should instead consider using `AF_XDP`.


We can also compromise and instead give user the choice?
 * Default if no XDP prog is loaded, fail and provide usage-help to select dump-methods

Dump-methods being:
 * Use `--af-packet` / --tcpdump (tcpdump libpcap live-capture)
 * Use `--xdp` (loads xdp_prog on interface)
 * Use -`-af-xdp` (loads xdp_prog that will steal all packets)

The last `af-xdp` is NOT for milestone#1 release.

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> We can also compromise and instead give user the choice?
>  * Default if no XDP prog is loaded, fail and provide usage-help to select dump-methods
>
> Dump-methods being:
>  * Use `--af-packet` / --tcpdump (tcpdump libpcap live-capture)
>  * Use `--xdp` (loads xdp_prog on interface)
>  * Use -`-af-xdp` (loads xdp_prog that will steal all packets)
>
> The last `af-xdp` is NOT for milestone#1 release.

This SGTM :)

**Comment by chaudron** [comment]
This is a nice to have, but not something for the 1.0 milestone, we can add this later. For now, there is already an example in the manpage on how to do this with other tools in this package.

**Comment by chaudron** [comment]
Adding note to self, we should not attach a dummy program and then do fentry/fexit, but make the fentry function THE xdp program.
