### ISSUE TITLE
Unable to compile xdp-tools on centos7.9

### ISSUE THREAD

**Issue by a783706** [xdp-project/xdp-tools#313]
hello，
Unable to compile xdp-tools on centos7.9
My kernel version is 5.5.0, gcc version is 9.3, bpftool version is 5.4.15, clang version is 11，and I installed the latest libbpf.
Compiling xdp-tools will prompt bpftool doesn't support skeleton generation.

![2](https://user-images.githubusercontent.com/73113823/231525698-e92d51e1-ef9b-4288-bc7b-87c995bd3879.PNG)

**Comment by tohojo** [comment]
Well, that means you'll need a newer version of bpftool... :)

**Comment by a783706** [comment]
@tohojo   hello, I installed the latest bpftool and libbpf, and I can compile xdp-filter normally. When I run it will prompt Could not find BPF working dir - bpffs not mounted?
![2](https://user-images.githubusercontent.com/73113823/231857271-0fc47005-969e-4f85-b386-1deea9abd222.PNG)

**Comment by hhoffstaette** [comment]
> @tohojo hello, I installed the latest bpftool and libbpf, and I can compile xdp-filter normally. When I run it will prompt Could not find BPF working dir - bpffs not mounted? 

bpffs is a virtual file system. I had the same issue when updating the xdp-tools package in Gentoo and added [this post-installation info](https://github.com/gentoo/gentoo/pull/30005/commits/a0bd7e379cc419fccf83d2f77886ad6de6ffb2b2#diff-21117478e4558b5620e1a2ca6f8605852c40c821da7624f5313ce8ebcd06d6ccR72). That should get you going.

**Comment by a783706** [comment]
@hhoffstaette Thanks，how do i use it. are there detailed steps.

https://github.com/gentoo/gentoo/pull/30005/commits/a0bd7e379cc419fccf83d2f77886ad6de6ffb2b2#diff-21117478e4558b5620e1a2ca6f8605852c40c821da7624f5313ce8ebcd06d6ccR72

**Comment by hhoffstaette** [comment]
@a783706 I'm not sure what you mean, did you read the message text? You need to run either the manual mount command (to test it until the next reboot) or add the bpffs entry to your /etc/fstab.

**Comment by a783706** [comment]
@hhoffstaette Thanks, I see, I'm not very familiar with English.

**Comment by hhoffstaette** [comment]
> Thanks, I see, I'm not very familiar with English.

I see - sorry, I did not mean to be impolite. Let us know if the mount commands work or how we can help further.

**Comment by tohojo** [comment]
a783706 ***@***.***> writes:

> @hhoffstaette yes, it's already working.
> I have a question, why can I load the XDP driver when the NIC does not have multi-queue.
>
> If I remember correctly, XDP can only run in skb mode if the NIC does
> not have multiqueue enabled.

Nope, XDP support has nothing to do with multiqueue; the driver just
needs to implement the XDP support for XDP to work in native (driver) mode...

**Comment by a783706** [comment]
@tohojo  ok, thank you.
