### ISSUE TITLE
Clean up utility program lock if pid no longer exists

### ISSUE THREAD

**Issue by tohojo** [xdp-project/xdp-tools#317]
The command line utilities take a runtime lock to prevent concurrently running
multiple instances, but if the utility crashes before releasing the lock,
subsequent invocations refuse to run before the lock is manually cleared out, as
noted here:

https://nick-black.com/dankwiki/index.php/Extended_disquisitions_pertaining_to_eXpress_data_paths_%28XDP%29

We really should clean this up and either rethink the locking completely, or at
least clean up stale locks instead of just bailing out.

**Comment by hiqsociety** [comment]
having this problem too, pls help update or provide a solution to this!

./xdp-filter status
Unable to read PID from lockfile: File exists
