### ISSUE TITLE
Unable to use xdp-trafficgen

### ISSUE THREAD

**Issue by vahsek300501** [xdp-project/xdp-tools#330]
I want to generate udp traffic using xdp-trafficgen. but when I run the following command it gives out the error

command: sudo ./xdp-trafficgen udp eno1

The error is as follows
![image](https://github.com/xdp-project/xdp-tools/assets/58917332/f63ccb1c-8a42-4ab7-aca0-ad39a642854f)

I have installed libbpf as a submodule along with this repository

**Comment by tohojo** [comment]
Yeah, unfortunately, xdp-trafficgen requires features from newer libbpf versions. You can force the configure script to use the submodule version of libbpf by running it as follows: `FORCE_SUBDIR_LIBBPF=1 ./configure`

**Comment by vahsek300501** [comment]
Yeah it worked. Thanks a lot
