### ISSUE TITLE
Help.  configure failed

### ISSUE THREAD

**Issue by xjj210130** [xdp-project/xdp-tools#334]
Hi :
    I do as following:
    1: git clone https://github.com/xdp-project/xdp-project.git
    2: cd  xdp-tools
    3: mkdir build && cd build
    4: ../configure
  but this is wrong message : bpftool doesn't support skeleton generation. The code is following:

`if $BPFTOOL gen help 2>&1 | grep 'gen skeleton.*name' > /dev/null; then
        bpftool_version=$($BPFTOOL version | head -n 1)
	echo "using $bpftool_version"
    else
	echo "bpftool doesn't support skeleton generation"
        exit 1
    fi`

 
 My worn env is :  centos 7.  clang 14.0.6 llvm 14.0.6  gcc 11.2.1.  Bpftool is also installed.

However, i delete this code from configure. But make is wrong.  This wrong is in  [xdp_sample.c](https://github.com/xdp-project/xdp-tools/blob/master/lib/util/xdp_sample.c)  code number is 255.

How to fix this problem. Thanks.

**Comment by tohojo** [comment]
xjj210130 ***@***.***> writes:

> Hi :
>     I do as following:
>     1: git clone https://github.com/xdp-project/xdp-project.git
>     2: cd  xdp-tools
>     3: mkdir build && cd build
>     4: ../configure
>   but this is wrong message : bpftool doesn't support skeleton
>     generation.

The message it not wrong. You'll just need to update to a newer version
of bpftool...

**Comment by xjj210130** [comment]
In fact .I do the following:
 uname -a :
 Linux localhost.localdomain 5.15.46linux-5.15.46 
gcc version:   2.33
build with code:
  1:  cd  /usr/src/kernels/linux-5.15.46/tools/bpf/bpftool
  2: make 
   but this is wrong Error: failed to load BTF from /usr/src/kernels/linux-5.15.46/vmlinux: No such file or directory
  however ,the file /usr/src/kernels/linux-5.15.46/vmlinux is exist.

the second method: use yum 
 1: download bpftool-5.15.46-1.mga8.x86_64.rpm
 2:  yum localinstall bpftool-5.15.46-1.mga8.x86_64.rpm
but the following wrong is appear:
  错误：软件包：bpftool-5.15.46-1.mga8.x86_64 (/bpftool-5.15.46-1.mga8.x86_64)
          需要：libc.so.6(GLIBC_2.22)(64bit)
错误：软件包：bpftool-5.15.46-1.mga8.x86_64 (/bpftool-5.15.46-1.mga8.x86_64)
          需要：libc.so.6(GLIBC_2.26)(64bit)

pl: how to fixed it. Is it any easy way to install bpftool?
thanks
