### ISSUE TITLE
"Unable" to read output through pipes - large buffer size

### ISSUE THREAD

**Issue by enhaut** [xdp-project/xdp-tools#344]
Default large pipe buffer (64KiB on linux) causes issues with reading `xdp-bench` output using pipes.

I am actually trying to read `xdp-bench` output for further analysis, i am simply piping `stdout` to `stdin` of my application, however due to large pipe buffer `stdout` seems to be empty.

There are multiple ways to resolve this issue:

* set size of `stdout` (and eventually `stderr`) buffer to `0` so prints will be immediately flushed/printed to stdout
* flushing `stdout` buffer using `fflush(stdout)` once a while e.g. right after summary/sample line is printed: https://github.com/xdp-project/xdp-tools/blob/00ff5bf76f28f518acbd40a7aed7606ff21dc364/lib/util/xdp_sample.c#L1119
* setting system-wide pipe buffer size. However, I think that's pretty clumsy 

I've got a first option implemented and tested in my fork, see commit https://github.com/xdp-project/xdp-tools/commit/c608351b30544abf08c183a2ea85a6c135833692

**Comment by tohojo** [comment]
Hmm, fair point. I think I would prefer to add an explicit flush after newline; care to open a pull request to do that? :)
