### ISSUE TITLE
is libxdp going to support kernel generic attach/detach/query API for multi-progs?

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/xdp-tools#363]
Hi @tohojo 

I am curious to know if libxdp is going to support the new merged [generic attach/detach/query API for multi-progs](https://lore.kernel.org/all/20230719140858.13224-2-daniel@iogearbox.net/#r), it is not using priority, if libxdp is going to support it, does it mean libxdp will also stop using program priority in the future?

Thanks

**Comment by tohojo** [comment]
Yeah, we'll probably try to support that in some form, once it lands for
XDP as well. Details TBD; my initial thought is that libxdp will keep
using priorities to do its internal sorting when inserting new
programmes, but use the kernel APIs to insert a program in the right
place when adding/removing.

We won't be able to support atomic replacement of multiple programs at
once with the kernel mprog API, so not sure what to do about that...
