### ISSUE TITLE
libxdp without dispatcher

### ISSUE THREAD

**Issue by juerlink** [xdp-project/xdp-tools#366]
Hello everyone,
I want to use libxdp without dispatcher (LIBXDP_SKIP_DISPATCHER=1) together with an AF_XDP socket. This works so far, but when I close the socket with xsk_socket__delete(), I get the error "No XDP dispatcher found on ifindex X". Later it is not possible to open an AF_XDP socket again, because there is an error from libbpf / kernel: "libbpf: Kernel error message: XDP program already attached".
Is there a chance to unload the default AF_XDP program? xdp_program__detach() used by xsk_socket__delete() does not do the job, when the dispatcher is not used.
Thanks a lot.

**Comment by juerlink** [comment]
I tried -DDEBUG in defines.mk for CFLAGS, but did not get more prints. Is there a better way to turn on verbose logging?
Thanks

**Comment by tohojo** [comment]
juerlink ***@***.***> writes:

> I tried -DDEBUG in defines.mk for CFLAGS, but did not get more prints.
> Is there a better way to turn on verbose logging?

It has to be done at runtime with libxdp_set_print(). Have a look in
lib/util/logging.c for an example.

**Comment by juerlink** [comment]
This is the verbose output I get when xsk_socket__create() is called:
  libxdp: Looking for './xsk_def_xdp_prog.o'
  libxdp: Loading XDP program from './xsk_def_xdp_prog.o' section '(unknown)'
libbpf: elf: skipping unrecognized data section(8) .xdp_run_config
libbpf: elf: skipping unrecognized data section(9) xdp_metadata
  libxdp: Skipping dispatcher due to environment setting
  libxdp: Checking for kernel frags support
  libxdp: Looking for './xdp-dispatcher.o'
  libxdp: Loading XDP program from './xdp-dispatcher.o' section 'xdp_pass'
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
  libxdp: DATASEC '.xdp_run_config' not found.
  libxdp: Loaded XDP program xdp_pass, got fd 9
  libxdp: Duplicated fd 9 to 10 for prog xdp_pass
  libxdp: Kernel supports XDP programs with frags
  libxdp: Loaded XDP program xsk_def_prog, got fd 9
  libxdp: Duplicated fd 9 to 10 for prog xsk_def_prog
  libxdp: Replacing XDP fd -1 with 10 on ifindex 6

Then my AF_XDP test is running fine. At the end of the test I call xsk_socket__delete() and get those prints:
  libxdp: Acquired lock from /sys/fs/bpf/xdp with fd 12
  libxdp: Released lock fd 12
  libxdp: No XDP dispatcher found on ifindex 6

The message "No XDP dispatcher found on ifindex 6" is print in the function xdp_program__detach_multi(). "mp = xdp_multiprog__get_from_ifindex(ifindex);" returns -2 and the function xdp_program__detach_multi() return immediately. No XDP dispatcher is logical, as I set LIBXDP_SKIP_DISPATCHER to 1 in order to run without the dispatcher. I assume, the default "xsk_def_prog" is loaded. 

Thanks for your help

**Comment by tohojo** [comment]
juerlink ***@***.***> writes:

> This is the verbose output I get when xsk_socket__create() is called:
>   libxdp: Looking for './xsk_def_xdp_prog.o'
>   libxdp: Loading XDP program from './xsk_def_xdp_prog.o' section '(unknown)'
> libbpf: elf: skipping unrecognized data section(8) .xdp_run_config
> libbpf: elf: skipping unrecognized data section(9) xdp_metadata
>   libxdp: Skipping dispatcher due to environment setting
>   libxdp: Checking for kernel frags support
>   libxdp: Looking for './xdp-dispatcher.o'
>   libxdp: Loading XDP program from './xdp-dispatcher.o' section 'xdp_pass'
> libbpf: elf: skipping unrecognized data section(7) xdp_metadata
>   libxdp: DATASEC '.xdp_run_config' not found.
>   libxdp: Loaded XDP program xdp_pass, got fd 9
>   libxdp: Duplicated fd 9 to 10 for prog xdp_pass
>   libxdp: Kernel supports XDP programs with frags
>   libxdp: Loaded XDP program xsk_def_prog, got fd 9
>   libxdp: Duplicated fd 9 to 10 for prog xsk_def_prog
>   libxdp: Replacing XDP fd -1 with 10 on ifindex 6
>
> Then my AF_XDP test is running fine. At the end of the test I call xsk_socket__delete() and get those prints:
>   libxdp: Acquired lock from /sys/fs/bpf/xdp with fd 12
>   libxdp: Released lock fd 12
>   libxdp: No XDP dispatcher found on ifindex 6
>
> The message "No XDP dispatcher found on ifindex 6" is print in the
> function xdp_program__detach_multi(). "mp =
> xdp_multiprog__get_from_ifindex(ifindex);" returns -2 and the function
> xdp_program__detach_multi() return immediately. No XDP dispatcher is
> logical, as I set LIBXDP_SKIP_DISPATCHER to 1 in order to run without
> the dispatcher. I assume, the default "xsk_def_prog" is loaded.

Right, well that error message is actually a bit misleading: it actually
means "no XDP program found on the interface at all". All the unloading
code should work fine with a non-dispatcher program.

Could you try running 'xdp-loader status' while your application is
running to see if the XDP program shows up there?

**Comment by juerlink** [comment]
> Right, well that error message is actually a bit misleading: it actually means "no XDP program found on the interface at all". All the unloading code should work fine with a non-dispatcher program.

Hello and thanks for the reply and sorry for my late reply, I was out of office for some days.
For me it looks, as if unloading does not work, because if I start my application a second time, which calls xsk_socket__create() again, I get the following error message:

  libxdp: Looking for './xsk_def_xdp_prog.o'
  libxdp: Loading XDP program from './xsk_def_xdp_prog.o' section '(unknown)'
libbpf: elf: skipping unrecognized data section(8) .xdp_run_config
libbpf: elf: skipping unrecognized data section(9) xdp_metadata
  libxdp: Skipping dispatcher due to environment setting
  libxdp: Checking for kernel frags support
  libxdp: Looking for './xdp-dispatcher.o'
  libxdp: Loading XDP program from './xdp-dispatcher.o' section 'xdp_pass'
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
  libxdp: DATASEC '.xdp_run_config' not found.
  libxdp: Loaded XDP program xdp_pass, got fd 9
  libxdp: Duplicated fd 9 to 10 for prog xdp_pass
  libxdp: Kernel supports XDP programs with frags
  libxdp: Loaded XDP program xsk_def_prog, got fd 9
  libxdp: Duplicated fd 9 to 10 for prog xsk_def_prog
  libxdp: Replacing XDP fd -1 with 10 on ifindex 6
**libbpf: Kernel error message: XDP program already attached**
  libxdp: Error attaching XDP program to ifindex 6: Device or resource busy
  libxdp: XDP already loaded on device
ERROR: xsk_socket__create failed: -16
ERROR: xsk_configure_socket failed
ERROR: ecm_runxsk failed

> Could you try running 'xdp-loader status' while your application is running to see if the XDP program shows up there?
I have to find out, how this can be done. I'll come back.

Thanks

**Comment by tohojo** [comment]
juerlink ***@***.***> writes:

>> Right, well that error message is actually a bit misleading: it actually means "no XDP program found on the interface at all". All the unloading code should work fine with a non-dispatcher program.
>
> Hello and thanks for the reply and sorry for my late reply, I was out of office for some days.
> For me it looks, as if unloading does not work, because if I start my application a second time, which calls xsk_socket__create() again, I get the following error message:
>
>   libxdp: Looking for './xsk_def_xdp_prog.o'
>   libxdp: Loading XDP program from './xsk_def_xdp_prog.o' section '(unknown)'
> libbpf: elf: skipping unrecognized data section(8) .xdp_run_config
> libbpf: elf: skipping unrecognized data section(9) xdp_metadata
>   libxdp: Skipping dispatcher due to environment setting
>   libxdp: Checking for kernel frags support
>   libxdp: Looking for './xdp-dispatcher.o'
>   libxdp: Loading XDP program from './xdp-dispatcher.o' section 'xdp_pass'
> libbpf: elf: skipping unrecognized data section(7) xdp_metadata
>   libxdp: DATASEC '.xdp_run_config' not found.
>   libxdp: Loaded XDP program xdp_pass, got fd 9
>   libxdp: Duplicated fd 9 to 10 for prog xdp_pass
>   libxdp: Kernel supports XDP programs with frags
>   libxdp: Loaded XDP program xsk_def_prog, got fd 9
>   libxdp: Duplicated fd 9 to 10 for prog xsk_def_prog
>   libxdp: Replacing XDP fd -1 with 10 on ifindex 6
> **libbpf: Kernel error message: XDP program already attached**
>   libxdp: Error attaching XDP program to ifindex 6: Device or resource busy
>   libxdp: XDP already loaded on device
> ERROR: xsk_socket__create failed: -16
> ERROR: xsk_configure_socket failed
> ERROR: ecm_runxsk failed
>
>> Could you try running 'xdp-loader status' while your application is running to see if the XDP program shows up there?
> I have to find out, how this can be done. I'll come back.

Cool. I think we may need an strace of either xdp-loader (if that also
doesn't show the program), or you AF_XDP application itself, to figure
out which syscall is failing...

**Comment by juerlink** [comment]
Maybe there is a bug in my driver. What disturbs me is, if I use libbpf of kernel 5.10 my application can be started again and again without an error. The application uses xsk_socket__create() at the beginning and xsk_socket__delete() at the end. If the application is started with libxdp after the test with libbpf, I get that error "XDP program already attached". The same if the application is started twice with libxdp. I mean not simultaneously but restarted after it was finished.
Unloading and reloading my driver solves the problem for one run of the application. Might be, I do something wrong in the driver, that does not matter with the old libbpf, but matters with libxdp. I try to find that out. Perhaps a stripped version of the application helps me to isolate the problem.

**Comment by tohojo** [comment]
juerlink ***@***.***> writes:

> Maybe there is a bug in my driver. What disturbs me is, if I use libbpf of kernel 5.10 my application can be started again and again without an error. The application uses xsk_socket__create() at the beginning and xsk_socket__delete() at the end. If the application is started with libxdp after the test with libbpf, I get that error "XDP program already attached". The same if the application is started twice with libxdp. I mean not simultaneously but restarted after it was finished.
> Unloading and reloading my driver solves the problem for one run of the application. Might be, I do something wrong in the driver, that does not matter with the old libbpf, but matters with libxdp. I try to find that out. Perhaps a stripped version of the application helps me to isolate the problem.


Well, there are some changes between the libbpf and libxdp version in
how detachment works, and it may well be a bug in libxdp; but I can't
spot anything obviously wrong in the detach logic, so I'll need some
more information to figure out what's wrong :)

**Comment by juerlink** [comment]
I'll try to get more debug info and come back. Thanks a lot

**Comment by tohojo** [comment]
Alright, closing this then :)
