### ISSUE TITLE
idea to migrate xdp synproxy to xdp-tools or bpf-examaples repo

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/xdp-tools#367]
Hi @tohojo 

I have an idea to make it easy for user to consume the xdp synproxy  by migrating  (https://elixir.bootlin.com/linux/latest/source/tools/testing/selftests/bpf/progs/xdp_synproxy_kern.c) to either xdp-tools or bpf-examples repo. would you take such pull request?

**Comment by tohojo** [comment]
Vincent Li ***@***.***> writes:

> Hi @tohojo 
>
> I have an idea to make it easy for user to consume the xdp synproxy
> by migrating
> (https://elixir.bootlin.com/linux/latest/source/tools/testing/selftests/bpf/progs/xdp_synproxy_kern.c)
> to either xdp-tools or bpf-examples repo. would you take such pull
> request?

Sure! My immediate thought would be to have it start out in
bpf-examples, with the possibility of moving it to xdp-tools in the
future if it turns out that there is demand for it :)

**Comment by vincentmli** [comment]
xdp-tools seems better choice since  xdp-tools is shipped by some distros, that could potentially allow users to easily test it out, but yes we can start with bpf-examples. while I am compiling the xdp_synproxy_kern.c with xdp-tools, I noticed there are lot of compiling errors about u8/u16/u32 types and other data structure types error, but after I included a full vmlinux.h header which include all the types, no more compiling errors. I have thought about only include the types needed in xdp_synproxy_kern.c  in trimmed  `headers/bpf/vmlinux.h`, but I again ran into various type compiling errors, do you think it is worth the effort to only pick the types used in xdp_synproxy_kern.c to be included in `headers/bpf/vmlinux.h`?

**Comment by vincentmli** [comment]
I think I will add the proper `linux/xxx.h` headers in xdp_synproxy_kern.c, and missing u8/u16/u32 in `headers/bpf/vmlinux.h` so I don't need to include the full blown `vmlinux.h` headers.

**Comment by tohojo** [comment]
For the u** types specifically, we generally use the __-prefixed
versions in BPF code outside the kernel tree. A simple search & replace
should be sufficient for this. For vmlinux.h, there are already some
fragments in headers/vmlinux in the bpf-examples repo. Feel free to add
to those as needed, but try to keep it small - we don't want a full
kernel vmlinux in there.

**Comment by vincentmli** [comment]
ok, I will do that. I will send up a pr in bpf-examples repo
