### ISSUE TITLE
Request: mechanism to build static libxdp without dispatcher binaries

### ISSUE THREAD

**Issue by ajmmm** [xdp-project/xdp-tools#368]
Hi,

I'm the creator of a project that's relying heavily on AF_XDP for high performance networking. (Posted a few times on xdp-newbies with bugs etc.)

Our project is pure C and has xdptools as a git submodule, compiled only as static archives, which get linked at build time into our binaries.

We actually have a lot of infrastructure around XDP/BPF - our program effectively "runs" a NIC, reconfiguring it via netlink sockets. So, our build actively disables the dispatcher stuff that gets baked into libxdp.

We've been running a very specific version of libxdp for over a year now, namely to ensure throughout development we're building a known good version. The time has come to do some updates and I'm now building the latest commit in github.

**Issue Description**

When building latest libxdp as a static archive, it seems we're faced with build faults because we're actively turning off the embedded XDP dispatcher bits.

Eg:

```
<<snipped ...>>
  CCLD     odd.bin
/usr/bin/ld: /home/ajm/talon/dep/xdptools/lib/libxdp/libxdp.a(libxdp.o):(.data+0x38): undefined reference to `_binary_xdp_dispatcher_o_start'
/usr/bin/ld: /home/ajm/talon/dep/xdptools/lib/libxdp/libxdp.a(libxdp.o):(.data+0x40): undefined reference to `_binary_xdp_dispatcher_o_end'
/usr/bin/ld: /home/ajm/talon/dep/xdptools/lib/libxdp/libxdp.a(libxdp.o):(.data+0x50): undefined reference to `_binary_xsk_def_xdp_prog_o_start'
/usr/bin/ld: /home/ajm/talon/dep/xdptools/lib/libxdp/libxdp.a(libxdp.o):(.data+0x58): undefined reference to `_binary_xsk_def_xdp_prog_o_end'
/usr/bin/ld: /home/ajm/talon/dep/xdptools/lib/libxdp/libxdp.a(libxdp.o):(.data+0x68): undefined reference to `_binary_xsk_def_xdp_prog_5_3_o_start'
/usr/bin/ld: /home/ajm/talon/dep/xdptools/lib/libxdp/libxdp.a(libxdp.o):(.data+0x70): undefined reference to `_binary_xsk_def_xdp_prog_5_3_o_end'
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:633: odd.bin] Error 1
```

I can drop the `XDP_OBJS="" SHARED_XDP_OBJS=""` build-time override, but then the dispatcher stuff gets compiled and linked into libxdp, which in turn gets linked into the binaries I'm building. This isn't desirable from our perspective.

I know in libxdp.c these references are wrapped in `ifdef LIBXDP_STATIC` but that macro is defined in the build recipe after CPPFLAGS so I can't easily override it via the build environment.

**The Ask**

Would it be possible to add a build/configure option to just disable the dispatcher logic at build?

At present I think my only option would be to run sed over the xdptools Makefile before I build to drop the `-D LIBXDP_STATIC=1` flag which is a bit icky.

Thanks in advance :-)
Further notes below if it's useful.
Cheers!

**How xdptools is built in our project**

Example Makefile recipe to build xdptools (we wrapper creation of the xdptools/config.mk for reasons not relevant for this post).
```
xdptools-setup-config:
	if [ ! -f $(XDPTOOLS_CONFIG) ]; then \
		./xdptools_config.sh $(XDPTOOLS_PATH) $(XDPTOOLS_PRODUCTION); \
	fi

xdptools-build: xdptools-setup-config
	CFLAGS="$(CFLAGS)" $(MAKE) -C $(XDPTOOLS_PATH) BUILD_STATIC_ONLY=y V=$(V) XDP_OBJS="" XDP_SHARED_OBJS="" libxdp
```

**Resulting verbose build log for xdptools**

```
make[5]: Leaving directory '/home/ajm/talon/dep/xdptools/lib/libbpf/src'

  libxdp
make[5]: Entering directory '/home/ajm/talon/dep/xdptools/lib/libxdp'
mkdir -p ./staticobjs
sed -e "s|@PREFIX@|/usr/local|" \
		-e "s|@LIBDIR@|/usr/local/lib|" \
		-e "s|@VERSION@|"1.4.0"|" \
		< libxdp.pc.template > libxdp.pc
gcc -Wall -g -ggdb -O0 -I./libbpf/src/root/usr/include -DHAVE_ZLIB -DHAVE_ELF -std=gnu11 -Wextra -Werror -DBPF_DIR_MNT=\"/sys/fs/bpf\" -DBPF_OBJECT_PATH=\"/usr/local/lib/bpf\" -DMAX_DISPATCHER_ACTIONS=10 -DTOOLS_VERSION=\""1.4.0"\" -DLIBBPF_VERSION=\"unknown\" -DRUNDIR=\"/run\" -DHAVE_LIBBPF_PERF_BUFFER__CONSUME -DHAVE_LIBBPF_BTF__LOAD_FROM_KERNEL_BY_ID -DHAVE_LIBBPF_BTF__TYPE_CNT -DHAVE_LIBBPF_BPF_OBJECT__NEXT_MAP -DHAVE_LIBBPF_BPF_OBJECT__NEXT_PROGRAM -DHAVE_LIBBPF_BPF_PROGRAM__INSN_CNT -DHAVE_LIBBPF_BPF_PROGRAM__TYPE -DHAVE_LIBBPF_BPF_PROGRAM__FLAGS -DHAVE_LIBBPF_BPF_PROGRAM__EXPECTED_ATTACH_TYPE -DHAVE_LIBBPF_BPF_MAP_CREATE -DHAVE_LIBBPF_PERF_BUFFER__NEW_RAW -DHAVE_LIBBPF_BPF_XDP_ATTACH -DHAVE_LIBBPF_BPF_MAP__SET_AUTOCREATE -DHAVE_LIBBPF_BPF_PROG_TEST_RUN_OPTS -DHAVE_LIBBPF_BPF_XDP_QUERY -DHAVE_SECURE_GETENV -DDEBUG -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -I../libbpf/src/root/usr/include -DHAVE_ZLIB -DHAVE_ELF -std=gnu11 -Wextra -Werror -DBPF_DIR_MNT=\"/sys/fs/bpf\" -DBPF_OBJECT_PATH=\"/usr/local/lib/bpf\" -DMAX_DISPATCHER_ACTIONS=10 -DTOOLS_VERSION=\""1.4.0"\" -DLIBBPF_VERSION=\"unknown\" -DRUNDIR=\"/run\" -DHAVE_LIBBPF_PERF_BUFFER__CONSUME -DHAVE_LIBBPF_BTF__LOAD_FROM_KERNEL_BY_ID -DHAVE_LIBBPF_BTF__TYPE_CNT -DHAVE_LIBBPF_BPF_OBJECT__NEXT_MAP -DHAVE_LIBBPF_BPF_OBJECT__NEXT_PROGRAM -DHAVE_LIBBPF_BPF_PROGRAM__INSN_CNT -DHAVE_LIBBPF_BPF_PROGRAM__TYPE -DHAVE_LIBBPF_BPF_PROGRAM__FLAGS -DHAVE_LIBBPF_BPF_PROGRAM__EXPECTED_ATTACH_TYPE -DHAVE_LIBBPF_BPF_MAP_CREATE -DHAVE_LIBBPF_PERF_BUFFER__NEW_RAW -DHAVE_LIBBPF_BPF_XDP_ATTACH -DHAVE_LIBBPF_BPF_MAP__SET_AUTOCREATE -DHAVE_LIBBPF_BPF_PROG_TEST_RUN_OPTS -DHAVE_LIBBPF_BPF_XDP_QUERY -DHAVE_SECURE_GETENV -DDEBUG -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -I../../headers  -D LIBXDP_STATIC=1 -Wall -I../../headers -c libxdp.c -o staticobjs/libxdp.o
gcc -Wall -g -ggdb -O0 -I./libbpf/src/root/usr/include -DHAVE_ZLIB -DHAVE_ELF -std=gnu11 -Wextra -Werror -DBPF_DIR_MNT=\"/sys/fs/bpf\" -DBPF_OBJECT_PATH=\"/usr/local/lib/bpf\" -DMAX_DISPATCHER_ACTIONS=10 -DTOOLS_VERSION=\""1.4.0"\" -DLIBBPF_VERSION=\"unknown\" -DRUNDIR=\"/run\" -DHAVE_LIBBPF_PERF_BUFFER__CONSUME -DHAVE_LIBBPF_BTF__LOAD_FROM_KERNEL_BY_ID -DHAVE_LIBBPF_BTF__TYPE_CNT -DHAVE_LIBBPF_BPF_OBJECT__NEXT_MAP -DHAVE_LIBBPF_BPF_OBJECT__NEXT_PROGRAM -DHAVE_LIBBPF_BPF_PROGRAM__INSN_CNT -DHAVE_LIBBPF_BPF_PROGRAM__TYPE -DHAVE_LIBBPF_BPF_PROGRAM__FLAGS -DHAVE_LIBBPF_BPF_PROGRAM__EXPECTED_ATTACH_TYPE -DHAVE_LIBBPF_BPF_MAP_CREATE -DHAVE_LIBBPF_PERF_BUFFER__NEW_RAW -DHAVE_LIBBPF_BPF_XDP_ATTACH -DHAVE_LIBBPF_BPF_MAP__SET_AUTOCREATE -DHAVE_LIBBPF_BPF_PROG_TEST_RUN_OPTS -DHAVE_LIBBPF_BPF_XDP_QUERY -DHAVE_SECURE_GETENV -DDEBUG -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -I../libbpf/src/root/usr/include -DHAVE_ZLIB -DHAVE_ELF -std=gnu11 -Wextra -Werror -DBPF_DIR_MNT=\"/sys/fs/bpf\" -DBPF_OBJECT_PATH=\"/usr/local/lib/bpf\" -DMAX_DISPATCHER_ACTIONS=10 -DTOOLS_VERSION=\""1.4.0"\" -DLIBBPF_VERSION=\"unknown\" -DRUNDIR=\"/run\" -DHAVE_LIBBPF_PERF_BUFFER__CONSUME -DHAVE_LIBBPF_BTF__LOAD_FROM_KERNEL_BY_ID -DHAVE_LIBBPF_BTF__TYPE_CNT -DHAVE_LIBBPF_BPF_OBJECT__NEXT_MAP -DHAVE_LIBBPF_BPF_OBJECT__NEXT_PROGRAM -DHAVE_LIBBPF_BPF_PROGRAM__INSN_CNT -DHAVE_LIBBPF_BPF_PROGRAM__TYPE -DHAVE_LIBBPF_BPF_PROGRAM__FLAGS -DHAVE_LIBBPF_BPF_PROGRAM__EXPECTED_ATTACH_TYPE -DHAVE_LIBBPF_BPF_MAP_CREATE -DHAVE_LIBBPF_PERF_BUFFER__NEW_RAW -DHAVE_LIBBPF_BPF_XDP_ATTACH -DHAVE_LIBBPF_BPF_MAP__SET_AUTOCREATE -DHAVE_LIBBPF_BPF_PROG_TEST_RUN_OPTS -DHAVE_LIBBPF_BPF_XDP_QUERY -DHAVE_SECURE_GETENV -DDEBUG -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -I../../headers  -D LIBXDP_STATIC=1 -Wall -I../../headers -c xsk.c -o staticobjs/xsk.o
ar rcs libxdp.a staticobjs/libxdp.o staticobjs/xsk.o
make[5]: Leaving directory '/home/ajm/talon/dep/xdptools/lib/libxdp'
```

**Comment by tohojo** [comment]
Alasdair McWilliam ***@***.***> writes:

> Would it be possible to add a build/configure option to just disable
> the dispatcher logic at build?

Why? You don't actually say anything about what the problem with having
the dispatcher be part of the statically linked binary is?

**Comment by ajmmm** [comment]
> Why? You don't actually say anything about what the problem with having the dispatcher be part of the statically linked binary is?

Preference.

It's odd to provide a utility library that forces the assumption that the client-side implementation requires these extra bits. That assumption causes unnecessary build breaks when overridden. :(

**Comment by tohojo** [comment]
Alasdair McWilliam ***@***.***> writes:

>> Why? You don't actually say anything about what the problem with having the dispatcher be part of the statically linked binary is?
>
> Preference.
>
> It's odd to provide a utility library that forces the assumption that
> the client-side implementation requires these extra bits. That
> assumption causes unnecessary build breaks when overridden. :(

Well, don't override it then :)

The purpose of libxdp is to support multiple programs on a single
interface, which unfortunately requires the use of the dispatcher until
the kernel learns to do this natively. Building without it means that
half the library won't work, which does not seem like a mode that's
worth supporting...

**Comment by ajmmm** [comment]
> The purpose of libxdp is to support multiple programs on a single interface, which unfortunately requires the use of the dispatcher until the kernel learns to do this natively. Building without it means that half the library won't work, which does not seem like a mode that's worth supporting...

I do see your point, but the switch is already in the code to facilitate the shared library build!

I assert that by supporting my ask, you're not really creating a huge support nightmare for the libxdp project, but you would be enabling wider flexibility for the developer community. I'd see that as a great reason to support the ask!

> Well, don't override it then :)

I wouldn't if I could just press the existing 'off' switch without a hack ;-)

In all seriousness, if I provided a pull request that bubbles the `-D LIBXDP_STATIC=1` command-line parameter into a build-time switch that can be toggled, would it be accepted? (Absolutely happy to do the work.)

**Comment by tohojo** [comment]
It's not about the code size (as you note, that is quite small). It's
about the functionality: building in this mode would break the central
promise of libxdp, namely that two applications that both use libxdp
will be able to co-exist on the same interface. So disabling the
embedding of the dispatcher *is a bad idea* and actively breaks
functionality of the library. So I'd really recommend not doing that :)

**Comment by tohojo** [comment]
You're welcome :)
