### ISSUE TITLE
force xdp-tools to built with static link to libbpf.a and libxdp.a 

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/xdp-tools#369]
Hi @tohojo 

I noticed when I port xdp-synproxy to bpf-examples repo, the xdp-synproxy is built with static link to libbpf.a and libxdp.a which is good if I want to run xdp-synproxy in container environment so no dependencies on dynamic link to libbpf.so and libxdp.so. but xdp-tools is  built with dynamic link to libbpf which has libbpf.so dependencies when run xdp-tools in container environment, is there a way to force xdp-tools to be built with static link to libbpf.a and libxdp.a ? I looked the configure and Makefile, could not figure out how to do it properly.

**Comment by tohojo** [comment]
FORCE_SUBDIR_LIBBPF=1 ./configure

should do the trick :)

**Comment by vincentmli** [comment]
looks I asked the right question, but did not find the right answer myself :)
