### ISSUE TITLE
Support appending programs to a multiprog

### ISSUE THREAD

**Issue by tohojo** [xdp-project/xdp-tools#37]
If we switch the dispatcher config to not be read-only, we could support appending XDP programs to it as long as they are loaded in the right order. This would mean we could support loading them one at a time and actually running as multiprog, instead of requiring them to all be loaded at the same time.

It would still only be partial support until freplace multi-attach lands in the kernel; and we would also lose the dead code elimination the verifier currently does with the parts of the dispatcher that are unused. So not sure if this is work supporting?

**Comment by tohojo** [comment]
@chaudron @netoptimizer do you have any opinions on whether we should go for this?

**Comment by chaudron** [comment]
Closing as #87 has been merged.
