### ISSUE TITLE
does libxdp support bpf tail call another xdp program?

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/xdp-tools#375]
I have no tried but just want to ask before I try, if I use libxdp to attach one XDP program, within this one XDP program, it uses bpf tail call to another XDP program, would this work with libxdp? my guess is it probably would not work, right? @tohojo

**Comment by tohojo** [comment]
That works just fine :)

**Comment by vincentmli** [comment]
ok, great, I am going to port XDP DNS RRL  which uses tail call to bpf-example repo then :)
