### ISSUE TITLE
Stack smashing detected

### ISSUE THREAD

**Issue by xeome** [xdp-project/xdp-tools#383]
My xdp programs, xdp-loader and probably other xdp-tools are crashing:

```sh
$ sudo xdp-loader status
[sudo] password for xeome:
CURRENT XDP PROGRAM STATUS:

Interface        Prio  Program name      Mode     ID   Tag               Chain actions
--------------------------------------------------------------------------------------
*** stack smashing detected ***: terminated
[1]    5362 IOT instruction  sudo xdp-loader status
``` 

in my programs `xdp_program__attach` function is causing stack smashing. I'm linking with `-lbpf -lxdp`

I'm running arch linux with latest mainstream kernel (6.6.10)
xdp-tools version: 1.4.1
libxdp version: 1.4.1
libbpf version: 1.3.0

**Comment by tohojo** [comment]
Hmm, interesting. Did you compile xdp-tools yourself, or are you using
distro packages? Any chance you can try running this using a debugger
and getting a backtrace to where the crash is happening?

**Comment by xeome** [comment]
It appears the problem was with arch linux packaging, both my programs and xdp-tools work fine now. They updated it few days ago. Sorry about that. Closing this issue.

**Comment by tohojo** [comment]
Emin ***@***.***> writes:

> It appears the problem was with arch linux packaging, both my programs
> and xdp-tools work fine now. They updated it few days ago. Sorry about
> that. Closing this issue.

Alright, sounds good; thanks!
