### ISSUE TITLE
xdp-bench compilation error

### ISSUE THREAD

**Issue by hameedphr** [xdp-project/xdp-tools#392]
I am try compile xdp-bench using make. It is giving me following error
    GEN      xdp_redirect_cpumap.skel.h
/bin/sh: 1: gen: not found
make: *** [../lib/common.mk:124: xdp_redirect_cpumap.skel.h] Error 127

How can I resolve this error?  Please note that xdp-filter is compiled and working good.

**Comment by asu1int** [comment]
try to compile xdp-trafficgen, got the following error, can you help? It's on Fedora 37 if it matter

/bin/sh: line 1: gen: command not found
make: *** [../lib/common.mk:124: xdp_trafficgen.skel.h] Error 127

**Comment by tohojo** [comment]
asu1int ***@***.***> writes:

> try to compile xdp-trafficgen, got the following error, can you help? It's on Fedora 37 if it matter
>
> /bin/sh: line 1: gen: command not found
> make: *** [../lib/common.mk:124: xdp_trafficgen.skel.h] Error 127

You'll need to install bpftool and re-run configure...
