### ISSUE TITLE
Compilation Error: libbpf: map 'rx_cnt': unexpected def kind var.

### ISSUE THREAD

**Issue by elvinlife** [xdp-project/xdp-tools#396]
### Troubled by a compilation error:

The output of `./configure`:
```
Found clang binary 'clang-11' with version 11 (from 'Ubuntu clang version 11.0.0-2~ubuntu20.04.1')
/usr/sbin/bpftool
using /usr/lib/linux-tools/5.15.0-89-generic/bpftool v5.15.126
libbpf support: submodule v1.2.0
  perf_buffer__consume support: yes (submodule)
  btf__load_from_kernel_by_id support: yes (submodule)
  btf__type_cnt support: yes (submodule)
  bpf_object__next_map support: yes (submodule)
  bpf_object__next_program support: yes (submodule)
  bpf_program__insn_cnt support: yes (submodule)
  bpf_program__type support: yes (submodule)
  bpf_program__flags support: yes (submodule)
  bpf_program__expected_attach_type support: yes (submodule)
  bpf_map_create support: yes (submodule)
  perf_buffer__new_raw support: yes (submodule)
  bpf_xdp_attach support: yes (submodule)
  bpf_map__set_autocreate support: yes (submodule)
  bpf_prog_test_run_opts support: yes (submodule)
  bpf_xdp_query support: yes (submodule)
zlib support: yes
ELF support: yes
pcap support: yes
secure_getenv support: yes
cap-ng support: no
```

The error logs of `make`:
```
libbpf: map 'rx_cnt': unexpected def kind var.
Error: failed to open BPF object file: Invalid argument
make[1]: *** [../lib/common.mk:124: xdp_redirect_basic.skel.h] Error 255
make: *** [Makefile:40: xdp-bench] Error 2
```

Does anyone have experience with this error before? Any suggestion or help is appreciated, thank you!

**Comment by tohojo** [comment]
Hmm, no, this is odd. Could you please post:

- The full output of 'make' from a clean build
- The output of `bpftool btf dump file xdp-bench/xdp_redirect_basic.bpf.o`

Thanks!

**Comment by elvinlife** [comment]
Hi Toke,

Thank you for your reply! I've attached the full output of `make` and dump of `xdp_redirect_basic.bpf.o` in these two logs.
[make.log](https://github.com/xdp-project/xdp-tools/files/14377221/make.log)
[xdp_redirect_basic.log](https://github.com/xdp-project/xdp-tools/files/14377226/xdp_redirect_basic.log)

The output of `uname -a`is:
```
Linux networklab-host2 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tohojo** [comment]
Yongzhou Chen ***@***.***> writes:

> Hi Toke,
>
> Thank you for your reply! I've attached the full output of `make` and dump of `xdp_redirect_basic.bpf.o` in these two logs.
> [make.log](https://github.com/xdp-project/xdp-tools/files/14377221/make.log)
> [xdp_redirect_basic.log](https://github.com/xdp-project/xdp-tools/files/14377226/xdp_redirect_basic.log)

Great thanks! Looks like clang fails to generate BTF correctly for the
typedef'd map definitions. Which is probably a version thing; could you
please try a newer version of clang (you can install them from
https://apt.llvm.org/ ) and see if that helps?

**Comment by elvinlife** [comment]
Hi Toke,

Thank you for your reply and the suggestion! However, I've tried llvm-16, llvm-17, and llvm-18, and they all don't work and report error:
```
llc: error: llc: xdp-dispatcher.ll:10:40: error: expected type
@dispatcher_version = dso_local global ptr null, section "xdp_metadata", align 8, !dbg !21
```
This time, there's no local BTF file "./xdp-bench/xdp_redirect_basic.bpf.o". I've attached the output of the make here: 
[make.log](https://github.com/xdp-project/xdp-tools/files/14412237/make.log)

**Comment by tohojo** [comment]
Yongzhou Chen ***@***.***> writes:

> Hi Toke,
>
> Thank you for your reply and the suggestion! However, I've tried llvm-16, llvm-17, and llvm-18, and they all don't work and report error:
> ```
> llc: error: llc: xdp-dispatcher.ll:10:40: error: expected type
> @dispatcher_version = dso_local global ptr null, section "xdp_metadata", align 8, !dbg !21
> ```

Hmm, this looks like you have a mismatch between clang and llc versions;
try passing both explicitly to configure, like:

CLANG=clang-16 LLC=llc-16 ./configure

And then re-run make

**Comment by elvinlife** [comment]
Hi Toke, it works this time! Thank you so much for the help!
