### ISSUE TITLE
Does the release package not include binaries?

### ISSUE THREAD

**Issue by ami-GS** [xdp-project/xdp-tools#416]
Hi,

There is no binaries in release packages as far as I checked. (e.g. https://github.com/xdp-project/xdp-tools/releases/download/v1.4.2/xdp-tools-1.4.2.tar.gz)
Do we have to build by ourselves if we want newer libxdp.so, libbpf.so and xdp-dispatcher.o?

**Comment by tohojo** [comment]
Daiki AMINAKA ***@***.***> writes:

> Hi,
>
> There is no binaries in release packages as far as I checked. (e.g. https://github.com/xdp-project/xdp-tools/releases/download/v1.4.2/xdp-tools-1.4.2.tar.gz)
> Do we have to build by ourselves if we want newer libxdp.so, libbpf.so
> and xdp-dispatcher.o?

No, we don't include binaries as part of the release artifacts. If your
distro doesn't provide an updated package, you will have to build your
own :)

**Comment by ami-GS** [comment]
Thanks!
