### ISSUE TITLE
xdp-traffic generator not generating traffic to any interface

### ISSUE THREAD

**Issue by s4ndroar** [xdp-project/xdp-tools#421]
# xdp-trafficgen udp --dst-mac aa:bb:cc:dd:ee:ff --dst-addr fe80::1 --dst-port 10000 wlan0
Transmitting on wlan0 (ifindex 2)
lo->wlan0                       0 err/s                 0 xmit/s       
lo->wlan0                       0 err/s                 0 xmit/s       
lo->wlan0                       0 err/s                 0 xmit/s       
lo->wlan0                       0 err/s                 0 xmit/s       
lo->wlan0                       0 err/s                 0 xmit/s       
lo->wlan0                       0 err/s                 0 xmit/s    

uname -r 
6.8.5-arch1-1

sniffing the traffic on both interfaces also shows zero packets.

**Comment by tohojo** [comment]
s4ndroar ***@***.***> writes:

> # xdp-trafficgen udp --dst-mac aa:bb:cc:dd:ee:ff --dst-addr fe80::1 --dst-port 10000 wlan0

xdp-trafficgen requires XDP support on the target interface, which WiFi
devices do not have...

**Comment by s4ndroar** [comment]
"Is virtual Ethernet interface not supported?" It also not generating any packet for it.

**Comment by tohojo** [comment]
s4ndroar ***@***.***> writes:

> "Is virtual Ethernet interface not supported?" It also not generating
> any packet for it.

For veth you need to either enable GRO on veth peers, or load a dummy
XDP program on the *other* side of the veth pair (i.e., on the device
that would receive the traffic).
