### ISSUE TITLE
Couldn't open file 'xdp_drop.o': No such file or directory

### ISSUE THREAD

**Issue by forkyyy** [xdp-project/xdp-tools#424]
```
root@localhost:~# xdp-loader load -m skb -s xdp_drop eth0 xdp_drop.o
Couldn't open file 'xdp_drop.o': No such file or directory
root@localhost:~# ls -l xdp_drop.o
-rw-r--r-- 1 root root 8848 May 27 17:19 xdp_drop.o
root@localhost:~#

Any idea whats the issue? file was just compiled

**Comment by tohojo** [comment]
forkyyy ***@***.***> writes:

> ***@***.***:~# xdp-loader load -m skb -s xdp_drop eth0 xdp_drop.o
> Couldn't open file 'xdp_drop.o': No such file or directory
> ***@***.***:~# ls -l xdp_drop.o
> -rw-r--r-- 1 root root 8848 May 27 17:19 xdp_drop.o
> ***@***.***:~#
>
>
> Any idea whats the issue? file was just compiled

Wrong section name? Try running with -vv and see if there are any hints
in the verbose output...
