### ISSUE TITLE
xdp_program__attach results in segmentation fault

### ISSUE THREAD

**Issue by eliaspiette** [xdp-project/xdp-tools#426]
Hello, I am trying to run this file 
```
#include <bpf/libbpf.h>
#include <xdp/libxdp.h>



#define IFINDEX 1

int main()
{
  struct xdp_program *prog;
  int err;

  prog = xdp_program__open_file("simple.o", "simple", NULL);
  err = xdp_program__attach(prog, IFINDEX, XDP_MODE_NATIVE, 0);

  if (!err)
      xdp_program__detach(prog, IFINDEX, XDP_MODE_NATIVE, 0);

  xdp_program__close(prog);
  return 0;
}
```

where the bpf file simply returns xdp_pass.

However, it returns a segmentation fault in libbpf.c function :
```
int bpf_program__set_flags(struct bpf_program *prog, __u32 flags)
{
	if (prog->obj->loaded)
		return libbpf_err(-EBUSY);

	prog->prog_flags = flags;
	return 0;
}
```

Where the obj attribute is NULL. My kernel version is 6.5.0-35-generic.

however, loading with xdp-loader works well. Thus i ask for your assistance

**Comment by tohojo** [comment]
Which version of libbpf are you using?

**Comment by eliaspiette** [comment]
using apt show libbpf-dev gives me this
Source: libbpf (1.3.0-2build2)

**Comment by eliaspiette** [comment]
As for this issue #422, i used the libbpf version referenced by xdp-tools repo and it seems to have solved it.

**Comment by tohojo** [comment]
Great. Suspected you might be hitting that same libbpf bug; closing this issue, then :)
