### ISSUE TITLE
load custom xdp program with xsk_setup_xdp_prog

### ISSUE THREAD

**Issue by Baruch-Fridman** [xdp-project/xdp-tools#433]
As per my understanding this function loads the default program. The question is, is there a reason for this? That is, what is the reason that it is not possible to pass the name of the program as a parameter, then this program will be loaded and not the default?

**Comment by magnus-karlsson** [comment]
There are libbpf and libxdp functions you can use to load any arbitrary program. No reason to offer another interface for that.
