### ISSUE TITLE
xdpdump only capture RX packet?

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/xdp-tools#449]
I noticed when running `xdpdump -i red0 -w /tmp/red0.pcap` and `tcpdump -nn -r /tmp/red0.pcap`, it only shows packet received (RX) by `red0` interface, not packet transmitted (TX) by `red0` interface, I assume that is expected ?

**Comment by chaudron** [comment]
Hi @vincentmli this is expected, as XDP programs can only be attached on the ingress side of the NIC.
