### ISSUE TITLE
xdp-dump: allow tracing one or more specific programs in a multiprogram environment

### ISSUE THREAD

**Issue by chaudron** [xdp-project/xdp-tools#45]

**Comment by chaudron** [comment]
Removing this from v1.0.0 milestone as this was explicitly not committed. This will not happen in 10 weekdays till deadline.

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

> Removing this from v1.0.0 milestone as this was explicitly not
> committed. This will not happen in 10 weekdays till deadline.

Ah, right, didn't realise that was a deliberate omission; sorry about that :)

**Comment by chaudron** [comment]
Fixed in pull req #79
