### ISSUE TITLE
How to xdpdump for xdp_drop events?

### ISSUE THREAD

**Issue by matt-keys** [xdp-project/xdp-tools#456]
Hi all,
I posted this to ebpf reddit a week ago with no responses -- https://www.reddit.com/r/eBPF/comments/1guvuge/how_to_xdpdump_for_xdp_drop_events_only/

I'm struggling to understand how to use xdpdump to capture any xdp_drop events from a physical interface or a bridged interface. I've tried just capturing everything (xdpdump --load-xdp-mode skb --rx-capture entry,exit --load-xdp-program -i {interface} -w /path/to/pcap.pcapng) and then filtering in wireshark after, but the drop events are empty. I was using filters like 'frame.verdict.ebpf_xdp == 1'. I only see xdp_pass (== 2) events. I know the drops exist because I can see them increment in the interface stats as I capture.

I've also tried in promiscuous mode, ie 'xdpdump --load-xdp-mode skb --load-xdp-program -i vmbr0 -P -w ~/vmbr0.pcap', but that seems to remove xdp events all together from the capture.

skb seems to be the only filter mode available for this bridge interface.

Thanks,

Matt

**Comment by chaudron** [comment]
The drop count in ip stats are not XDP drops, they are drops at the hardware/driver level. If there are drops in XDP you can use the filters in your example.

**Comment by tohojo** [comment]
Matt Keys ***@***.***> writes:

> initialcount=$(ifconfig vmbr0 | grep drop | grep -v TX | awk '{ print $5 }')

These are regular netstack drops and have nothing to do with XDP. What
makes you think they are XDP-related?

**Comment by matt-keys** [comment]
> These are regular netstack drops and have nothing to do with XDP. What makes you think they are XDP-related?

I'm new to ebpf/xdp but I was intrigued by its positioning relative to netfilter. I rran across https://prototype-kernel.readthedocs.io/en/latest/networking/XDP/use-cases/xdp_use_case_ddos_scrubber.html#need-traffic-sampling-xdp-drop written circa 2016, then I ran across xdpdump description "This means that even packets that are dropped at the XDP layer can be captured via this tool". 

I was thinking that because XDP/eBPF is positioned before netfliter in the stack ( https://en.wikipedia.org/wiki/Express_Data_Path#/media/File:Netfilter-packet-flow.svg ) this would be possible.

**Comment by matt-keys** [comment]
Thanks for the clarification and tips! I'm still a little fuzzy here: 

> And *if* you install such a program that drops some (or all) packets,
*then* xdpdump can tell you which packets were dropped this way.

Is xdpdump not capturing *all* packets in the example command?

`xdpdump --load-xdp-mode skb --rx-capture entry,exit --load-xdp-program -i {interface} -w /path/to/pcap.pcapng`

If not, is it possible for xdpdump to show me everything including drops?

My goal is to capture what is being dropped (rx) *on the host itself* and dump just those frames to a pcap. My old school way of doing this would be to compare a switch port span/mirror capture to a localhost capture of 'tcpdump -s0 -n -i any' for differences.

**Comment by tohojo** [comment]
Matt Keys ***@***.***> writes:

>> It's capturing everything, but the drop status only pertains to whether the packet is dropped *by XDP itself*. It's perfectly possible that a packet will pass the XDP hook, pass there without being dropped (which is an XDP_PASS verdict), then proceed to the stack and still end up being dropped by some other component before reaching the netfilter hook. In which case it will show up as "xdp_pass" in xdpdump.
>
> That makes sense. Thanks again for the clarification! It'd be cool if there was an xdpdump switch to do such as comparison between xdp_pass and netfilter and dump those differences as something like xdp_drop so you could easily filter for them.

Yeah, I understand what you mean - having a "where did my packet go?"
kind of utility is useful in many situations! However, I don't think
xdpdump is the right place to have this functionality, this is more in
the realm of "cross-sytem packet tracing", for which there already exist
some other utilities, as I mentioned up-thread.

**Comment by matt-keys** [comment]
I modified the script I posted in reddit to ignore any reported value less than 5 seconds, run for an hour, then average out time between reported drops. This gives me a good idea of when the bursts of drops occur, ie every 5 minutes:

Drop count incremented: 1344 -> 1345 at 2024-11-26 13:39:46.305221297 (Time since last: 315.138296108 seconds)
Drop count incremented: 1348 -> 1349 at 2024-11-26 13:45:03.195076894 (Time since last: 315.114340936 seconds)
Drop count incremented: 1352 -> 1353 at 2024-11-26 13:50:20.098172576 (Time since last: 315.016968495 seconds)
...
Average time difference over 11 iterations: 315.08624067927272727272 seconds

Here's the modified script:

```
# Get the initial drop count
initialcount=$(ifconfig vmbr0 | grep drop | grep -v TX | awk '{ print $5 }')

# Check if the initial count is valid
if [[ -z "$initialcount" ]]; then
    echo "Error: Could not retrieve initial drop count from ifconfig."
    exit 1
fi

# Initialize variables for time tracking and statistics
last_timestamp=$(date +"%s.%N")
total_time_diff=0
iteration_count=0
end_time=$(date +%s)  # Get the current time in seconds
end_time=$((end_time + 3600))  # Run the loop for exactly 1 hour

# Infinite while loop with 1-hour duration
while [[ $(date +%s) -lt $end_time ]]; do
    # Get the current drop count
    currentcount=$(ifconfig vmbr0 | grep drop | grep -v TX | awk '{ print $5 }')

    # Check if the drop count has changed
    if [[ "$currentcount" -gt "$initialcount" ]]; then
        # Get the current timestamp in format like 2024-11-22 06:42:31.313649
        timestamp=$(date +"%Y-%m-%d %H:%M:%S.%N")

        # Calculate the time difference between the current and last timestamp
        current_epoch=$(date +"%s.%N")
        time_diff=$(echo "$current_epoch - $last_timestamp" | bc)

        # Only accumulate time_diff if it is greater than or equal to 5 seconds
        if (( $(echo "$time_diff >= 5" | bc -l) )); then
            total_time_diff=$(echo "$total_time_diff + $time_diff" | bc)
            iteration_count=$((iteration_count + 1))

            # Echo the change, timestamp, and time difference to stdout
            echo "Drop count incremented: $initialcount -> $currentcount at $timestamp (Time since last: $time_diff seconds)"
        fi

        # Update the initial count to the new count and store the current timestamp for the next iteration
        initialcount=$currentcount
        last_timestamp=$current_epoch
    fi

    # Wait 0.1 seconds before checking again
    sleep 0.1
done

# At the end of 1 hour, compute the average time_diff
if [[ $iteration_count -gt 0 ]]; then
    average_time_diff=$(echo "$total_time_diff / $iteration_count" | bc -l)
    echo "Average time difference over $iteration_count iterations: $average_time_diff seconds"
else
    echo "No drop count increments occurred during the 1-hour period."
fi
```

1. If you only see rx drop increment when NOT running a tcpdump capture of the interface in question, there's a good chance it was dropped by the kernel. See 2 below. When running tcpdump on the interface the kernel evidently stops incrementing the rx dropped counter. 

2. kernel.org ( https://docs.kernel.org/networking/statistics.html ) defines rx_dropped as:

rx_dropped
Number of packets received but not processed, e.g. due to lack of resources or unsupported protocol. For hardware interfaces this counter may include packets discarded due to L2 address filtering but should not include packets dropped by the device due to buffer exhaustion which are counted separately in rx_missed_errors (since procfs folds those two counters together).

Check the rx_missed_errors as well with `ethtool -S {interface} | grep -e drop -e missed` 

If you don't see anything in rx_missed_errors, then that leaves us with 'unsupported protocol' or 'packets discarded due to L2 address filtering'. 

3. pcap_diff (https://github.com/isginf/pcap-diff) is useful to compare physical interface xdpdump to bridge interface tcpdump. pcap_diff.py requires python3-scapy deb package. Usage: pcap_diff.py -i phyinterface-xdp.pcap -i bridgeinterface-tcpdump.pcap -o /path/output.pcap -f m

The -f m causes pcap_diff.py to ignore the mac difference. The xdpdump seems to produce some name resolution in the macs when I use `xdpdump --load-xdp-mode skb --rx-capture entry --load-xdp-program -i "$PHYSICAL_INTERFACE" --use-pcap -w "$CAPTURE_DIR/$PHYSICAL_INTERFACE-xdp.pcap` versus the tcpdump `tcpdump -s0 -n -Q in -i "$BRIDGE_INTERFACE" -w "$CAPTURE_DIR/$BRIDGE_INTERFACE-tcpdump.pcap". Without the '-f m' you'll see any difference.

**Comment by chaudron** [comment]
FYI there is a good project going on right now for tracing packets in the kernel (there is a dropmonitor feature). 

https://github.com/retis-org/retis 

You can search for online presentations about the tool at various conferences.
