### ISSUE TITLE
BUG REPORT: static bool kernel_has_frags_support(void)

### ISSUE THREAD

**Issue by eagle4968** [xdp-project/xdp-tools#459]
In this function realization:
test_prog = __xdp_program__find_file("xdp-dispatcher.o", NULL, "xdp_pass", NULL);
we get test_prog here, but test_prog->bpf_prog->obj is NULL, so it will find Segmentation fault in the following line:
bpf_program__set_flags(test_prog->bpf_prog, BPF_F_XDP_HAS_FRAGS);

which would use test_prog->bpf_prog->obj->loaded

**Comment by tohojo** [comment]
eagle4968 ***@***.***> writes:

> In this function realization:
> test_prog = __xdp_program__find_file("xdp-dispatcher.o", NULL, "xdp_pass", NULL);
> we get test_prog here, but test_prog->bpf_prog->obj is NULL, so it will find Segmentation fault in the following line:
> bpf_program__set_flags(test_prog->bpf_prog, BPF_F_XDP_HAS_FRAGS);
>
> which would use test_prog->bpf_prog->obj->loaded

Erm, huh? How does test_prog->bpf_prog->obj end up being NULL? What
version of libbpf are you seeing this with?

**Comment by eagle4968** [comment]
> eagle4968 ***@***.***> writes:
> In this function realization: test_prog = __xdp_program__find_file("xdp-dispatcher.o", NULL, "xdp_pass", NULL); we get test_prog here, but test_prog->bpf_prog->obj is NULL, so it will find Segmentation fault in the following line: bpf_program__set_flags(test_prog->bpf_prog, BPF_F_XDP_HAS_FRAGS); which would use test_prog->bpf_prog->obj->loaded
> Erm, huh? How does test_prog->bpf_prog->obj end up being NULL? What version of libbpf are you seeing this with?


the version of libbpf I used is 1.6.0

bpf_prog = bpf_object__find_program_by_name(obj, prog_name);

Maybe this function didn't fill obj in bpf_prog

**Comment by tohojo** [comment]
eagle4968 ***@***.***> writes:

>> eagle4968 ***@***.***> writes:
>> In this function realization: test_prog = __xdp_program__find_file("xdp-dispatcher.o", NULL, "xdp_pass", NULL); we get test_prog here, but test_prog->bpf_prog->obj is NULL, so it will find Segmentation fault in the following line: bpf_program__set_flags(test_prog->bpf_prog, BPF_F_XDP_HAS_FRAGS); which would use test_prog->bpf_prog->obj->loaded
>> Erm, huh? How does test_prog->bpf_prog->obj end up being NULL? What version of libbpf are you seeing this with?
>
>
> the version of libbpf I used is 1.6.0
>
> bpf_prog = bpf_object__find_program_by_name(obj, prog_name);
>
> Maybe this function didn't fill obj in bpf_prog

Erm no, there is no way libbpf initialises a BPF object without
initialising the prog->obj pointers. So there has to be something else
going on here.

Could you please provide the exact instructions for how to reproduce the
segfault crash you saw? Including exact compilation instructions and
commit hashes for both xdp-tools and libbpf?

**Comment by eagle4968** [comment]
I compiled  [<advanced03-AF_XDP>](url)  from https://github.com/xdp-project/xdp-tutorial, which used libxdp and libbpf
run the program like this:
./bin/userspace_executable -d eno1 --filename ./lib/ebpf_program.o --progname xdp_sock_prog -N
it got crash...

![bpf](https://github.com/user-attachments/assets/21e8c8d9-1c63-42d2-ad0d-fc7e7feeef88)

**Comment by tohojo** [comment]
eagle4968 ***@***.***> writes:

> I compiled  [<advanced03-AF_XDP>](url)  from https://github.com/xdp-project/xdp-tutorial, which used libxdp and libbpf
> run the program like this:
> ./bin/userspace_executable -d eno1 --filename ./lib/ebpf_program.o --progname xdp_sock_prog -N
> it got crash...

Where does 'userspace_executable' come from? Is this something you wrote
yourself?

Also, what's the output of `./configure` in the toplevel xdp-tutorial directory?

**Comment by eagle4968** [comment]
I get 'userspace_executable' from compiling [af_xdp_user.c](https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_user.c),  and 'ebpf_program.o' comes from compiling [af_xdp_kern.c](https://github.com/xdp-project/xdp-tutorial/blob/master/advanced03-AF_XDP/af_xdp_kern.c)

the problem is I used '-O0' when compiling ebpf_program.o. When I change it to '-O2', it runs correctly.

Thank you very much!

**Comment by Alexanderchens** [comment]
i am facing the same problem and i dont see why the way we compile ebpf_program.o can cause to 'test_prog->bpf_prog->obj==null'.  My xdp_prog_kern.o has already used '-O2'

![Image](https://github.com/user-attachments/assets/ada3a9c0-2eee-4457-9e61-1d1cf958b4c2)
