### ISSUE TITLE
Update headers/linux/ to the latest?

### ISSUE THREAD

**Issue by chaudron** [xdp-project/xdp-tools#7]
Does it make sense to update the headers/linux/ files, or is there a specific cadence for doing this?

**Comment by tohojo** [comment]
Eelco Chaudron <notifications@github.com> writes:

> Does it make sense to update the headers/linux/ files, or is there a
> specific cadence for doing this?

Well if you run into a case where you need something from a newer
version of a header, feel free to update it. Otherwise, not much reason
to update them just because, is there? :)
