### ISSUE TITLE
It possible to use xdp-filter on many interfaces?

### ISSUE THREAD

**Issue by 2cfg** [xdp-project/xdp-tools#70]
If I use NIC bonding and I want to protect all the slave interfaces, can I use xdp-filter?

**Comment by tohojo** [comment]
2cfg <notifications@github.com> writes:

> If I use NIC bonding and I want to protect all the slave interfaces,
> can I use xdp-filter?

Don't see why not - but you'd have to load xdp-filter on all the
component interfaces (it'll run before the bonding code kicks in, and
won't be aware that there's a bond there at all).

If you just run 'xdp-filter load' on each interface they'll all end up
sharing the same filter maps, though, so this should be pretty
straight-forward...

**Comment by 2cfg** [comment]
Thanks a lot. I'll try to use it.
