### ISSUE TITLE
Unable to load xdp-filter

### ISSUE THREAD

**Issue by tattipravin** [xdp-project/xdp-tools#72]
After compiling i tried to load xdp-filter with defaults, but it always fails to load with the below error.

sudo ./xdp-filter load -m skb enp0s8

libxdp: Failed to load program xdpfilt_alw_all: Argument list too long
Couldn't attach XDP program on iface 'enp0s8': Argument list too long(-7)

**Comment by tohojo** [comment]
Tatti Pravin <notifications@github.com> writes:

> After compiling i tried to load xdp-filter with defaults, but it always fails to load with the below error.
>
> libxdp: Failed to load program xdpfilt_alw_all: Argument list too long
> Couldn't attach XDP program on iface 'enp0s8': Argument list too long(-7)

Sounds like your kernel is too old? What version is that?
