### ISSUE TITLE
xdp-loader - Couldn't attach XDP program

### ISSUE THREAD

**Issue by c-sh0** [xdp-project/xdp-tools#82]
Hello, 
I seem to be having a problem loading xdp programs using xdp-loader. 
When attempting to load the basic01-xdp-pass XDP program from the [xdp-tutorial](https://github.com/xdp-project/xdp-tutorial) examples, I get the following error's
```
xdp-loader load -v --mode skb lo basic01-xdp-pass/xdp_pass_kern.o

Current rlimit is infinity or 0. Not raising
Loading 1 files on interface 'lo'.
XDP program 0: Run prio: 50. Chain call actions: XDP_PASS
libxdp: Couldn't open BPF file
Couldn't attach XDP program on iface 'lo': Kernel verifier blocks program loading(-4007)
```
Notable errors from `-vv`
```
libbpf: added 60 insn from .text to prog xdp/dispatcher
libbpf: load bpf program failed: Invalid argument
libbpf: -- BEGIN DUMP LOG ---
libbpf:
Validating prog0() func#1...
btf_vmlinux is malformed
Arg#0 type PTR in prog0() is not supported yet.
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

libbpf: -- END LOG --
libbpf: failed to load program 'xdp/dispatcher'
libbpf: failed to load object '/usr/lib64/bpf/xdp-dispatcher.o'
libxdp: Couldn't open BPF file
Couldn't attach XDP program on iface 'lo': Kernel verifier blocks program loading(-4007)
```
**Testing Environment**
- Virtualbox VM  (Memory: 2G)
- CentOS Linux release 8.3.2011
- Kernel: 5.10.2-1.el8.elrepo.x86_64
- xdp-tools-1.0.1-1.el8.x86_64 (centos appstream repository)

Compiling the tool from source produces the same errors. 
Loading xdp program's using iproute works fine. 

Thanks in advance for the help.

**Comment by tohojo** [comment]
csh <notifications@github.com> writes:

> Hello, 
> I seem to be having a problem loading xdp programs using xdp-loader. 
> When attempting to load the basic01-xdp-pass XDP program from the [xdp-tutorial](https://github.com/xdp-project/xdp-tutorial) examples, I get the following error's
> ```
> xdp-loader load -v --mode skb lo basic01-xdp-pass/xdp_pass_kern.o
>
> Current rlimit is infinity or 0. Not raising
> Loading 1 files on interface 'lo'.
> XDP program 0: Run prio: 50. Chain call actions: XDP_PASS
> libxdp: Couldn't open BPF file
> Couldn't attach XDP program on iface 'lo': Kernel verifier blocks program loading(-4007)
> ```
> Notable errors from `-vv`
> ```
> libbpf: added 60 insn from .text to prog xdp/dispatcher
> libbpf: load bpf program failed: Invalid argument
> libbpf: -- BEGIN DUMP LOG ---
> libbpf:
> Validating prog0() func#1...
> btf_vmlinux is malformed

Hmm, this looks like the kernel was compiled without BTF information?

> Arg#0 type PTR in prog0() is not supported yet.

Not sure what that would lead to this error, though...

**Comment by c-sh0** [comment]
> prog0() func#1... btf_vmlinux is malformed
> Hmm, this looks like the kernel was compiled without BTF information?

Kernel config
```
grep 'BTF' /boot/config-5.10.2-1.el8.elrepo.x86_64
# CONFIG_DEBUG_INFO_BTF is not set
```

> Arg#0 type PTR in prog0() is not supported yet.
> Not sure what that would lead to this error, though...

I must have missed something when i first compiled from source, doing a clean re-compile of xdp-loader here is what i get,
```
xdp-loader]# ls
Makefile  README.org  tests  xdp-dispatcher.o  xdp-loader  xdp-loader.c

xdp-loader]# ./xdp-loader load -vv --mode skb lo ../../xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o
[.. snip ..]

libxdp: DATASEC '.xdp_run_config' not found.
libxdp: Verified XDP dispatcher version 1 <= 1
libxdp: Loading multiprog dispatcher for 1 programs
libbpf: map 'xdp_disp.rodata': created successfully, fd=5
libbpf: added 60 insn from .text to prog xdp/dispatcher
libbpf: load bpf program failed: Invalid argument
libbpf: -- BEGIN DUMP LOG ---
libbpf:
Validating prog0() func#1...
btf_vmlinux is malformed
Arg#0 type PTR in prog0() is not supported yet.
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

libbpf: -- END LOG --
libbpf: failed to load program 'xdp/dispatcher'
libbpf: failed to load object './xdp-dispatcher.o'
libxdp: Got verifier error while loading dispatcher.
libxdp: Falling back to loading single prog without dispatcher
libxdp: Loaded XDP program xdp_prog_simple, got fd 5
libxdp: Replacing XDP fd -1 with 5 on ifindex 1
```
Despite the above errors it's loading the example programs
```
xdp-loader]# ./xdp-loader status
CURRENT XDP PROGRAM STATUS:

Interface        Prio  Program name     Mode     ID   Tag               Chain actions
-------------------------------------------------------------------------------------
lo                     xdp_prog_simple  skb      169  3b185187f1855c4c
```

**Comment by tohojo** [comment]
csh <notifications@github.com> writes:

>> prog0() func#1... btf_vmlinux is malformed
>> Hmm, this looks like the kernel was compiled without BTF information?
>
> Kernel config
> ```
> grep 'BTF' /boot/config-5.10.2-1.el8.elrepo.x86_64
> # CONFIG_DEBUG_INFO_BTF is not set
> ```

Hmm, yeah, that's what I thought. Still not sure why that is needed, but
I'm technically on holiday now, so will hold off on going digging until
the new year :)

>> Arg#0 type PTR in prog0() is not supported yet.
>> Not sure what that would lead to this error, though...
>
> I must have missed something when i first compiled from source, doing a clean re-compile of xdp-loader here is what i get,
> ```
> xdp-loader]# ls
> Makefile  README.org  tests  xdp-dispatcher.o  xdp-loader  xdp-loader.c
>
> xdp-loader]# ./xdp-loader load -vv --mode skb lo ../../xdp-tutorial/basic01-xdp-pass/xdp_pass_kern.o
> [.. snip ..]
>
> libxdp: DATASEC '.xdp_run_config' not found.
> libxdp: Verified XDP dispatcher version 1 <= 1
> libxdp: Loading multiprog dispatcher for 1 programs
> libbpf: map 'xdp_disp.rodata': created successfully, fd=5
> libbpf: added 60 insn from .text to prog xdp/dispatcher
> libbpf: load bpf program failed: Invalid argument
> libbpf: -- BEGIN DUMP LOG ---
> libbpf:
> Validating prog0() func#1...
> btf_vmlinux is malformed
> Arg#0 type PTR in prog0() is not supported yet.
> processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
>
> libbpf: -- END LOG --
> libbpf: failed to load program 'xdp/dispatcher'
> libbpf: failed to load object './xdp-dispatcher.o'
> libxdp: Got verifier error while loading dispatcher.
> libxdp: Falling back to loading single prog without dispatcher
> libxdp: Loaded XDP program xdp_prog_simple, got fd 5
> libxdp: Replacing XDP fd -1 with 5 on ifindex 1
> ```
> Despite the above errors it's loading the example programs

Yeah, I implemented the fallback quite recently; but glad to see it
working. This means you will only be able to load a single program on
the interface, but other than that it should just work :)

**Comment by tohojo** [comment]
Closing this issue - please reopen if you're still experiencing problems.
